set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports g_clk]
set_property PACKAGE_PIN T3 [get_ports g_clk]

################# AD ####################################
set_property IOSTANDARD LVCMOS33 [get_ports {AD_DB[*]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {AD_OS[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports AD_BUSY1]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CONVST]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CS0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_BUSY0]
set_property IOSTANDARD LVCMOS33 [get_ports AD_Rst]
set_property IOSTANDARD LVCMOS33 [get_ports AD_RD]
set_property IOSTANDARD LVCMOS33 [get_ports AD_CS1]
set_property PACKAGE_PIN AB16 [get_ports {AD_DB[0]}]
set_property PACKAGE_PIN AA16 [get_ports {AD_DB[1]}]
set_property PACKAGE_PIN AA15 [get_ports {AD_DB[2]}]
set_property PACKAGE_PIN AB14 [get_ports {AD_DB[3]}]
set_property PACKAGE_PIN AA14 [get_ports {AD_DB[4]}]
set_property PACKAGE_PIN AB13 [get_ports {AD_DB[5]}]
set_property PACKAGE_PIN AA13 [get_ports {AD_DB[6]}]
set_property PACKAGE_PIN AB12 [get_ports {AD_DB[7]}]
set_property PACKAGE_PIN AB11 [get_ports {AD_DB[8]}]
set_property PACKAGE_PIN AA11 [get_ports {AD_DB[9]}]
set_property PACKAGE_PIN AB10 [get_ports {AD_DB[10]}]
set_property PACKAGE_PIN AA10 [get_ports {AD_DB[11]}]
set_property PACKAGE_PIN AB9 [get_ports {AD_DB[12]}]
set_property PACKAGE_PIN AA9 [get_ports {AD_DB[13]}]
#set_property PACKAGE_PIN V12  [get_ports {AD_OS[2]}]
#set_property PACKAGE_PIN W12  [get_ports {AD_OS[1]}]
#set_property PACKAGE_PIN W14  [get_ports {AD_OS[0]}]
set_property PACKAGE_PIN AA17 [get_ports AD_CONVST]
set_property PACKAGE_PIN AB20 [get_ports AD_BUSY1]
set_property PACKAGE_PIN AB19 [get_ports AD_BUSY0]
set_property PACKAGE_PIN AB18 [get_ports AD_CS0]
set_property PACKAGE_PIN AA20 [get_ports AD_CS1]
set_property PACKAGE_PIN AB17 [get_ports AD_Rst]
set_property PACKAGE_PIN AA18 [get_ports AD_RD]
################# AD ####################################

################# ARM IF ####################################
#set_property IOSTANDARD LVCMOS33 [get_ports {AB[*]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {DB[*]}]
#set_property IOSTANDARD LVCMOS33 [get_ports BUF_NWE]
#set_property IOSTANDARD LVCMOS33 [get_ports BUF_NRD]
#set_property IOSTANDARD LVCMOS33 [get_ports BUF_NCS3]
#set_property IOSTANDARD LVCMOS33 [get_ports ARM_IRQ0]
#set_property PACKAGE_PIN T21  [get_ports {AB[0]}]
#set_property PACKAGE_PIN R20  [get_ports {AB[1]}]
#set_property PACKAGE_PIN P22  [get_ports {AB[2]}]
#set_property PACKAGE_PIN P21  [get_ports {AB[3]}]
#set_property PACKAGE_PIN Y20  [get_ports {AB[4]}]
#set_property PACKAGE_PIN T20  [get_ports {AB[5]}]
#set_property PACKAGE_PIN W21  [get_ports {AB[6]}]
#set_property PACKAGE_PIN V22  [get_ports {AB[7]}]
#set_property PACKAGE_PIN V21  [get_ports {AB[8]}]
#set_property PACKAGE_PIN U22  [get_ports {AB[9]}]
#set_property PACKAGE_PIN F22  [get_ports {DB[15]}]
#set_property PACKAGE_PIN F21  [get_ports {DB[14]}]
#set_property PACKAGE_PIN D22  [get_ports {DB[13]}]
#set_property PACKAGE_PIN B21  [get_ports {DB[12]}]
#set_property PACKAGE_PIN B22  [get_ports {DB[11]}]
#set_property PACKAGE_PIN C20  [get_ports {DB[10]}]
#set_property PACKAGE_PIN C22  [get_ports {DB[9]}]
#set_property PACKAGE_PIN D21  [get_ports {DB[8]}]
#set_property PACKAGE_PIN L22  [get_ports {DB[7]}]
#set_property PACKAGE_PIN L21  [get_ports {DB[6]}]
#set_property PACKAGE_PIN K22  [get_ports {DB[5]}]
#set_property PACKAGE_PIN J22  [get_ports {DB[4]}]
#set_property PACKAGE_PIN J21  [get_ports {DB[3]}]
#set_property PACKAGE_PIN H21  [get_ports {DB[2]}]
#set_property PACKAGE_PIN G22  [get_ports {DB[1]}]
#set_property PACKAGE_PIN G21  [get_ports {DB[0]}]
#set_property PACKAGE_PIN Y21  [get_ports BUF_NCS3]
#set_property PACKAGE_PIN W22  [get_ports BUF_NRD]
#set_property PACKAGE_PIN AB21 [get_ports BUF_NWE]
#set_property PACKAGE_PIN Y22  [get_ports ARM_IRQ0]
################# ARM IF ####################################

################# ARM3358 IF ####################################
set_property PACKAGE_PIN D22 [get_ports {AMBUS_AB[0]}]
set_property PACKAGE_PIN D21 [get_ports {AMBUS_AB[1]}]
set_property PACKAGE_PIN F22 [get_ports {AMBUS_AB[2]}]
set_property PACKAGE_PIN F21 [get_ports {AMBUS_AB[3]}]
set_property PACKAGE_PIN E22 [get_ports {AMBUS_AB[4]}]
set_property PACKAGE_PIN H21 [get_ports {AMBUS_AB[5]}]
set_property PACKAGE_PIN J22 [get_ports {AMBUS_AB[6]}]
set_property PACKAGE_PIN J21 [get_ports {AMBUS_AB[7]}]
set_property PACKAGE_PIN G22 [get_ports {AMBUS_AB[8]}]
set_property PACKAGE_PIN K22 [get_ports {AMBUS_AB[9]}]
set_property PACKAGE_PIN G21 [get_ports {AMBUS_AB[10]}]
set_property PACKAGE_PIN U20 [get_ports {AMBUS_DB[15]}]
set_property PACKAGE_PIN U22 [get_ports {AMBUS_DB[14]}]
set_property PACKAGE_PIN T21 [get_ports {AMBUS_DB[13]}]
set_property PACKAGE_PIN T22 [get_ports {AMBUS_DB[12]}]
set_property PACKAGE_PIN R20 [get_ports {AMBUS_DB[11]}]
set_property PACKAGE_PIN P22 [get_ports {AMBUS_DB[10]}]
set_property PACKAGE_PIN P21 [get_ports {AMBUS_DB[9]}]
set_property PACKAGE_PIN N20 [get_ports {AMBUS_DB[8]}]
set_property PACKAGE_PIN V21 [get_ports {AMBUS_DB[7]}]
set_property PACKAGE_PIN V22 [get_ports {AMBUS_DB[6]}]
set_property PACKAGE_PIN W21 [get_ports {AMBUS_DB[5]}]
set_property PACKAGE_PIN W22 [get_ports {AMBUS_DB[4]}]
set_property PACKAGE_PIN Y21 [get_ports {AMBUS_DB[3]}]
set_property PACKAGE_PIN AA21 [get_ports {AMBUS_DB[2]}]
set_property PACKAGE_PIN AA22 [get_ports {AMBUS_DB[1]}]
set_property PACKAGE_PIN AB21 [get_ports {AMBUS_DB[0]}]
set_property PACKAGE_PIN B21 [get_ports AMBUS_CE]
set_property PACKAGE_PIN B22 [get_ports AMBUS_RE]
set_property PACKAGE_PIN C22 [get_ports AMBUS_WE]
set_property PACKAGE_PIN Y22 [get_ports ARM_IRQ0]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_IRQ0]
set_property IOSTANDARD LVCMOS33 [get_ports {AMBUS_AB[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AMBUS_DB[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports AMBUS_WE]
set_property IOSTANDARD LVCMOS33 [get_ports AMBUS_RE]
set_property IOSTANDARD LVCMOS33 [get_ports AMBUS_CE]
set_property PULLUP true [get_ports AMBUS_WE]
set_property PULLUP true [get_ports AMBUS_RE]
set_property PULLUP true [get_ports AMBUS_CE]
################# ARM3358 IF ####################################

################# CPLD ####################################
set_property IOSTANDARD LVCMOS33 [get_ports {CPLD_out[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CPLD_in[*]}]
set_property PACKAGE_PIN B9 [get_ports {CPLD_in[0]}]
set_property PACKAGE_PIN A10 [get_ports {CPLD_in[1]}]
set_property PACKAGE_PIN B10 [get_ports {CPLD_in[2]}]
set_property PACKAGE_PIN A11 [get_ports {CPLD_in[3]}]
set_property PACKAGE_PIN C11 [get_ports {CPLD_in[4]}]
set_property PACKAGE_PIN A12 [get_ports {CPLD_in[5]}]
set_property PACKAGE_PIN C12 [get_ports {CPLD_in[6]}]
set_property PACKAGE_PIN A13 [get_ports {CPLD_in[7]}]
set_property PACKAGE_PIN B13 [get_ports {CPLD_in[8]}]
set_property PACKAGE_PIN A14 [get_ports {CPLD_in[9]}]
set_property PACKAGE_PIN B14 [get_ports {CPLD_in[10]}]
set_property PACKAGE_PIN B15 [get_ports {CPLD_in[11]}]
set_property PACKAGE_PIN A16 [get_ports {CPLD_in[12]}]
set_property PACKAGE_PIN B16 [get_ports {CPLD_in[13]}]
set_property PACKAGE_PIN A17 [get_ports {CPLD_in[14]}]
set_property PACKAGE_PIN C17 [get_ports {CPLD_in[15]}]

set_property PACKAGE_PIN A3 [get_ports {CPLD_out[0]}]
set_property PACKAGE_PIN B3 [get_ports {CPLD_out[1]}]
set_property PACKAGE_PIN A4 [get_ports {CPLD_out[2]}]
set_property PACKAGE_PIN C4 [get_ports {CPLD_out[3]}]
set_property PACKAGE_PIN A5 [get_ports {CPLD_out[4]}]
set_property PACKAGE_PIN C5 [get_ports {CPLD_out[5]}]
set_property PACKAGE_PIN A6 [get_ports {CPLD_out[6]}]
set_property PACKAGE_PIN B6 [get_ports {CPLD_out[7]}] 

set_property PACKAGE_PIN B8 [get_ports {CPLD_out[8]}]
set_property PACKAGE_PIN A9 [get_ports {CPLD_out[9]}]
set_property PACKAGE_PIN A7 [get_ports {CPLD_out[10]}]
set_property PACKAGE_PIN B7 [get_ports {CPLD_out[11]}]
################# 3 电平板子 PWM ########################
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_6]
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_5]
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_4]
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_3]
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_2]
set_property IOSTANDARD LVCMOS33 [get_ports PWMC_1]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_6]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_5]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_4]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_3]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_2]
set_property IOSTANDARD LVCMOS33 [get_ports PWMB_1]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_6]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_5]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_4]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_3]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_2]
set_property IOSTANDARD LVCMOS33 [get_ports PWMA_1]
set_property PACKAGE_PIN Y5 [get_ports PWMA_1]
set_property PACKAGE_PIN AB4 [get_ports PWMA_2]
set_property PACKAGE_PIN AA6 [get_ports PWMA_3]
set_property PACKAGE_PIN AB5 [get_ports PWMA_4]
set_property PACKAGE_PIN AA7 [get_ports PWMA_5]
set_property PACKAGE_PIN AB2 [get_ports PWMB_1]
set_property PACKAGE_PIN AA2 [get_ports PWMB_2]
set_property PACKAGE_PIN AB3 [get_ports PWMB_3]
set_property PACKAGE_PIN AA3 [get_ports PWMB_4]
set_property PACKAGE_PIN AA8 [get_ports PWMB_5]
set_property PACKAGE_PIN Y3 [get_ports PWMC_1]
set_property PACKAGE_PIN W1 [get_ports PWMC_2]
set_property PACKAGE_PIN AA1 [get_ports PWMC_3]
set_property PACKAGE_PIN Y1 [get_ports PWMC_4]
set_property PACKAGE_PIN W2 [get_ports PWMC_5]
set_property PACKAGE_PIN V1 [get_ports PWMC_6]
set_property PACKAGE_PIN AB7 [get_ports PWMB_6]
set_property PACKAGE_PIN AB6 [get_ports PWMA_6]

set_property IOSTANDARD LVCMOS33 [get_ports IGBTC_ERR_4]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTC_ERR_3]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTC_ERR_2]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTC_ERR_1]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTB_ERR_4]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTB_ERR_3]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTB_ERR_2]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTB_ERR_1]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTA_ERR_4]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTA_ERR_3]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTA_ERR_2]
set_property IOSTANDARD LVCMOS33 [get_ports IGBTA_ERR_1]
set_property PACKAGE_PIN M1 [get_ports IGBTA_ERR_1]
set_property PACKAGE_PIN M2 [get_ports IGBTA_ERR_2]
set_property PACKAGE_PIN N1 [get_ports IGBTA_ERR_3]
set_property PACKAGE_PIN N3 [get_ports IGBTA_ERR_4]
set_property PACKAGE_PIN P1 [get_ports IGBTB_ERR_1]
set_property PACKAGE_PIN P2 [get_ports IGBTB_ERR_2]
set_property PACKAGE_PIN T2 [get_ports IGBTB_ERR_3]
set_property PACKAGE_PIN R2 [get_ports IGBTB_ERR_4]
set_property PACKAGE_PIN U2 [get_ports IGBTC_ERR_1]
set_property PACKAGE_PIN T1 [get_ports IGBTC_ERR_2]
#set_property PACKAGE_PIN V1 [get_ports IGBTC_ERR_3]
#set_property PACKAGE_PIN Y7 [get_ports IGBTC_ERR_3] 
set_property PACKAGE_PIN V4 [get_ports IGBTC_ERR_3]
set_property PACKAGE_PIN U1 [get_ports IGBTC_ERR_4]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_OE2]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_OE1]
set_property PACKAGE_PIN A2 [get_ports PWM_OE2]
set_property PACKAGE_PIN L1 [get_ports PWM_OE1]
################# 3 电平板子 PWM ########################

################### 3 电平板子 光纤/接插件信�? #################
set_property IOSTANDARD LVCMOS33 [get_ports FIBER_TX_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports FIBER_RX_IN]
set_property IOSTANDARD LVCMOS33 [get_ports CN6_7_CONNECT]
set_property PACKAGE_PIN G1 [get_ports FIBER_RX_IN]
set_property PACKAGE_PIN F1 [get_ports FIBER_TX_OUT]
set_property PACKAGE_PIN K1 [get_ports CN6_7_CONNECT]
################### 3 电平板子 光纤/接插件信�? #################

########################## TEST #########################
set_property IOSTANDARD LVCMOS33 [get_ports Test_Pin*]
set_property PACKAGE_PIN T16 [get_ports Test_Pin3]
set_property PACKAGE_PIN J1 [get_ports Test_Pin1]
set_property PACKAGE_PIN P16 [get_ports Test_Pin2]
########################## TEST #########################

#======================= timing =======================
create_clock -period 40.000 -name g_clk -waveform {20.000 40.000} [get_ports g_clk]
create_generated_clock -name CLK200M [get_pins -hierarchical -regexp .*/CLKOUT1]
create_generated_clock -name CLK25M [get_pins -hierarchical -regexp .*/CLKOUT2]
set_false_path -from [get_generated_clocks CLK200M] -to [get_generated_clocks CLK25M]
set_false_path -from [get_generated_clocks CLK25M] -to [get_generated_clocks CLK200M]
set_false_path -from [get_generated_clocks CLK25M] -to [get_generated_clocks CLK200M]
set_false_path -from [get_pins -hierarchical -regexp {.*dBuf_wr_sys_reg\[.*\]\[.*\]/C}]  -to [get_pins -hierarchical  -regexp {.*wdata_reg\[.*\]\[.*\]/D}]
set_false_path -from [get_pins -hierarchical -regexp {.*dBuf_wr_sys_reg\[.*\]\[.*\]/C}]  -to [get_pins -hierarchical  -regexp {.*full_word_data_send_reg\[.*\]/D}]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_cs_n_r0_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_re_n_r0_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_re_n_r1_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_we_n_r0_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_we_n_r1_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_false_path -from [get_cells ARM_comm_Inst/arm3358_gpmc_cs_n_r1_reg] -to [get_cells ARM_comm_Inst/dBuf_wr_tx_reg[*][*]]
set_max_delay -from [get_cells ARM_comm_Inst/arm3358_gpmc_cs_n_r0_reg] -to [get_cells {ARM_comm_Inst/wave_inst/samp_inst/rd_ack_cnt_reg[*]}] 5.000
set_max_delay -from [get_cells {GridPll_V10_Inst/Unit_Delay6_out1_reg[18]}] -to [get_cells {ARM_comm_Inst/wave_inst/wdata_reg[8][*]}] 10.000

set_property MAX_FANOUT 52 [get_nets -hier -regexp {.*ARM_comm_Inst/comm_state_inst/chk_code_inst/temp_data\[.*\]}]
set_false_path -from [get_pins -hier -regexp {.*comm_state_inst/wr_cache_reg\[2[2345]\d\]\[.*\]/C}] -to [get_pins -hier -regexp {.*comm_state_inst/chk_code_inst/data_o_reg\[.*\]/D}]
#======================= debug =======================
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk200m]
#======================= ce =======================
set_max_delay -from [get_ports AMBUS_CE] -to [get_ports {AMBUS_DB[*]}] 15.000
set_max_delay -from [get_ports AMBUS_RE] -to [get_ports {AMBUS_DB[*]}] 15.000




