// -------------------------------------------------------------
// 
// File Name: Work_BitFilter_V11\BitFilter_V11\BitFilter_V11.v
// Created: 2017-04-13 10:45:52
// 
// Generated by MATLAB 8.6 and HDL Coder 3.7
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: BitFilter_V11
// Source Path: BitFilter_V11/BitFilter_V11
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module BitFilter_V11
          (
           g_clk,
           Rst_n,
           Pulse_4096Hz,
           Filter_Reset,
           In0,
           In1,
           In2,
           In3,
           In4,
           In5,
           In6,
           In7,
           In8,
           In9,
           In10,
           In11,
           In12,
           In13,
           In14,
           In15,
           BitFltedOut0,
           BitFltedOut1,
           BitFltedOut2,
           BitFltedOut3,
           BitFltedOut4,
           BitFltedOut5,
           BitFltedOut6,
           BitFltedOut7,
           BitFltedOut8,
           BitFltedOut9,
           BitFltedOut10,
           BitFltedOut11,
           BitFltedOut12,
           BitFltedOut13,
           BitFltedOut14,
           BitFltedOut15
          );


  input   g_clk;
  input   Rst_n;
  input   Pulse_4096Hz;
  input   Filter_Reset;
  input   In0;
  input   In1;
  input   In2;
  input   In3;
  input   In4;
  input   In5;
  input   In6;
  input   In7;
  input   In8;
  input   In9;
  input   In10;
  input   In11;
  input   In12;
  input   In13;
  input   In14;
  input   In15;
  output  BitFltedOut0;
  output  BitFltedOut1;
  output  BitFltedOut2;
  output  BitFltedOut3;
  output  BitFltedOut4;
  output  BitFltedOut5;
  output  BitFltedOut6;
  output  BitFltedOut7;
  output  BitFltedOut8;
  output  BitFltedOut9;
  output  BitFltedOut10;
  output  BitFltedOut11;
  output  BitFltedOut12;
  output  BitFltedOut13;
  output  BitFltedOut14;
  output  BitFltedOut15;


  reg [3:0] Unit_Delay43_out1;  // ufix4
  wire [3:0] Add1_out1;  // ufix4
  wire CT41_out1;
  wire CT1_out1;
  reg  Unit_Delay4_out1;
  wire Switch4_out1;
  wire Switch1_out1;
  wire Or2_out1;
  wire Switch5_out1;
  reg  Unit_Delay6_out1;
  wire CT207_out1;
  reg  Unit_Delay121_out1;
  wire Switch308_out1;
  wire Switch307_out1;
  wire Or1_out1;
  wire Switch309_out1;
  reg  Unit_Delay122_out1;
  wire CT2_out1;
  wire CT4_out1;
  wire CT3_out1;
  wire CT8_out1;
  wire CT5_out1;
  wire CT7_out1;
  wire CT6_out1;
  wire CT13_out1;
  wire CT9_out1;
  wire CT12_out1;
  wire CT11_out1;
  wire CT17_out1;
  wire CT14_out1;
  wire CT16_out1;
  wire CT15_out1;
  wire signal1;
  wire s;
  wire signal1_1;
  wire s_1;
  wire signal1_2;
  wire s_2;
  wire signal1_3;
  wire s_3;
  wire signal1_4;
  wire s_4;
  wire signal1_5;
  wire s_5;
  wire signal1_6;
  wire s_6;
  wire signal1_7;
  wire s_7;
  wire signal1_8;
  wire s_8;
  wire signal1_9;
  wire s_9;
  wire signal1_10;
  wire s_10;
  wire signal1_11;
  wire s_11;
  wire signal1_12;
  wire s_12;
  wire signal1_13;
  wire s_13;
  wire signal1_14;
  wire s_14;
  wire signal1_15;
  wire signal1_16;
  wire signal1_17;
  wire signed [7:0] Switch58_out1;  // int8
  wire signed [7:0] Switch3_out1;  // int8
  reg signed [7:0] Unit_Delay22_out1;  // int8
  wire signed [7:0] Switch27_out1;  // int8
  wire signed [7:0] Switch46_out1;  // int8
  wire signed [7:0] Bus_Creator12_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay1_out1;  // int8
  wire signed [7:0] Switch7_out1;  // int8
  wire signed [7:0] Bus_Creator1_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay7_out1;  // int8
  wire signed [7:0] Switch10_out1;  // int8
  reg signed [7:0] Unit_Delay3_out1;  // int8
  wire signed [7:0] Switch13_out1;  // int8
  wire signed [7:0] Bus_Creator2_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay11_out1;  // int8
  wire signed [7:0] Switch21_out1;  // int8
  wire signed [7:0] Bus_Creator5_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay9_out1;  // int8
  wire signed [7:0] Switch24_out1;  // int8
  wire signed [7:0] Bus_Creator4_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay15_out1;  // int8
  wire signed [7:0] Switch15_out1;  // int8
  wire signed [7:0] Bus_Creator7_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay13_out1;  // int8
  wire signed [7:0] Switch18_out1;  // int8
  wire signed [7:0] Bus_Creator6_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay28_out1;  // int8
  wire signed [7:0] Switch52_out1;  // int8
  wire signed [7:0] Bus_Creator9_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay17_out1;  // int8
  wire signed [7:0] Switch55_out1;  // int8
  wire signed [7:0] Bus_Creator8_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay32_out1;  // int8
  wire signed [7:0] Switch31_out1;  // int8
  wire signed [7:0] Bus_Creator11_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay30_out1;  // int8
  wire signed [7:0] Switch34_out1;  // int8
  wire signed [7:0] Bus_Creator10_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay19_out1;  // int8
  wire signed [7:0] Switch42_out1;  // int8
  wire signed [7:0] Bus_Creator14_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay34_out1;  // int8
  wire signed [7:0] Switch48_out1;  // int8
  wire signed [7:0] Bus_Creator13_out1_signal2;  // int8
  reg signed [7:0] Unit_Delay25_out1;  // int8
  wire signed [7:0] Switch36_out1;  // int8
  wire signed [7:0] Bus_Creator16_out1_signal2;  // int8
  wire CT10_out1;
  wire signed [7:0] Switch2_out1;  // int8
  wire signed [7:0] Switch28_out1;  // int8
  wire Dy2_relop1;
  reg signed [7:0] Unit_Delay21_out1;  // int8
  wire signed [7:0] Switch39_out1;  // int8
  wire signed [7:0] signal2;  // int8
  wire signed [7:0] s_15;  // int8
  wire signed [7:0] signal2_1;  // int8
  wire signed [7:0] s_16;  // int8
  wire signed [7:0] signal2_2;  // int8
  wire signed [7:0] s_17;  // int8
  wire signed [7:0] signal2_3;  // int8
  wire signed [7:0] s_18;  // int8
  wire signed [7:0] signal2_4;  // int8
  wire signed [7:0] s_19;  // int8
  wire signed [7:0] signal2_5;  // int8
  wire signed [7:0] s_20;  // int8
  wire signed [7:0] signal2_6;  // int8
  wire signed [7:0] s_21;  // int8
  wire signed [7:0] signal2_7;  // int8
  wire signed [7:0] s_22;  // int8
  wire signed [7:0] signal2_8;  // int8
  wire signed [7:0] s_23;  // int8
  wire signed [7:0] signal2_9;  // int8
  wire signed [7:0] s_24;  // int8
  wire signed [7:0] signal2_10;  // int8
  wire signed [7:0] s_25;  // int8
  wire signed [7:0] signal2_11;  // int8
  wire signed [7:0] s_26;  // int8
  wire signed [7:0] signal2_12;  // int8
  wire signed [7:0] s_27;  // int8
  wire signed [7:0] signal2_13;  // int8
  wire signed [7:0] s_28;  // int8
  wire signed [7:0] signal2_14;  // int8
  wire signed [7:0] s_29;  // int8
  wire signed [7:0] signal2_15;  // int8
  wire signed [7:0] signal2_16;  // int8
  wire signed [7:0] signal2_17;  // int8
  wire signed [7:0] Add3_out1;  // int8
  reg  Unit_Delay23_out1;
  wire Bus_Creator12_out1_signal3;
  reg  Unit_Delay2_out1;
  wire Switch30_out1;
  wire Switch8_out1;
  wire Bus_Creator1_out1_signal3;
  reg  Unit_Delay8_out1;
  wire Switch11_out1;
  reg  Unit_Delay5_out1;
  wire Switch14_out1;
  wire Bus_Creator2_out1_signal3;
  reg  Unit_Delay12_out1;
  wire Switch22_out1;
  wire Bus_Creator5_out1_signal3;
  reg  Unit_Delay10_out1;
  wire Switch25_out1;
  wire Bus_Creator4_out1_signal3;
  reg  Unit_Delay16_out1;
  wire Switch16_out1;
  wire Bus_Creator7_out1_signal3;
  reg  Unit_Delay14_out1;
  wire Switch19_out1;
  wire Bus_Creator6_out1_signal3;
  reg  Unit_Delay29_out1;
  wire Switch53_out1;
  wire Bus_Creator9_out1_signal3;
  reg  Unit_Delay27_out1;
  wire Switch56_out1;
  wire Bus_Creator8_out1_signal3;
  reg  Unit_Delay33_out1;
  wire Switch32_out1;
  wire Bus_Creator11_out1_signal3;
  reg  Unit_Delay31_out1;
  wire Switch35_out1;
  wire Bus_Creator10_out1_signal3;
  reg  Unit_Delay20_out1;
  wire Switch43_out1;
  wire Bus_Creator14_out1_signal3;
  reg  Unit_Delay18_out1;
  wire Switch49_out1;
  wire Bus_Creator13_out1_signal3;
  reg  Unit_Delay26_out1;
  wire Switch37_out1;
  wire Bus_Creator16_out1_signal3;
  reg  Unit_Delay24_out1;
  wire Switch40_out1;
  wire signal3;
  wire s_30;
  wire signal3_1;
  wire s_31;
  wire signal3_2;
  wire s_32;
  wire signal3_3;
  wire s_33;
  wire signal3_4;
  wire s_34;
  wire signal3_5;
  wire s_35;
  wire signal3_6;
  wire s_36;
  wire signal3_7;
  wire s_37;
  wire signal3_8;
  wire s_38;
  wire signal3_9;
  wire s_39;
  wire signal3_10;
  wire s_40;
  wire signal3_11;
  wire s_41;
  wire signal3_12;
  wire s_42;
  wire signal3_13;
  wire s_43;
  wire signal3_14;
  wire s_44;
  wire signal3_15;
  wire signal3_16;
  wire signal3_17;
  wire Switch29_out1;
  wire Switch47_out1;


  // <S1>/Add1
  assign Add1_out1 = 4'b0001 + Unit_Delay43_out1;



  // <S1>/Unit Delay43
  // 
  // <S1>/Goto57
  // 
  // <S1>/From10
  // 
  // <S1>/Goto57
  // 
  // <S1>/From756
  // 
  // <S1>/Goto57
  // 
  // <S1>/From7
  // 
  // <S1>/Goto57
  // 
  // <S1>/From5
  // 
  // <S1>/Goto57
  // 
  // <S1>/From48
  // 
  // <S1>/Goto57
  // 
  // <S1>/From45
  // 
  // <S1>/Goto57
  // 
  // <S1>/From42
  // 
  // <S1>/Goto57
  // 
  // <S1>/From39
  // 
  // <S1>/Goto57
  // 
  // <S1>/From35
  // 
  // <S1>/Goto57
  // 
  // <S1>/From33
  // 
  // <S1>/Goto57
  // 
  // <S1>/From31
  // 
  // <S1>/Goto57
  // 
  // <S1>/From27
  // 
  // <S1>/Goto57
  // 
  // <S1>/From24
  // 
  // <S1>/Goto57
  // 
  // <S1>/From21
  // 
  // <S1>/Goto57
  // 
  // <S1>/From19
  // 
  // <S1>/Goto57
  // 
  // <S1>/From15
  // 
  // <S1>/Goto57
  // 
  // <S1>/From13
  // 
  // <S1>/Goto57
  // 
  // <S1>/From123
  always @(posedge g_clk)
    begin : Unit_Delay43_process
      if (Rst_n == 1'b0) begin
        Unit_Delay43_out1 <= 4'b0000;
      end
      else begin
        Unit_Delay43_out1 <= Add1_out1;
      end
    end



  // <S1>/CT41
  assign CT41_out1 = Unit_Delay43_out1 == 4'b0000;



  // <S1>/CT1
  assign CT1_out1 = Unit_Delay43_out1 == 4'b0000;



  // <S1>/Switch4
  assign Switch4_out1 = (Filter_Reset == 1'b0 ? Unit_Delay4_out1 :
              1'b1);



  // <S1>/Switch1
  assign Switch1_out1 = (CT1_out1 == 1'b0 ? Switch4_out1 :
              1'b0);



  // <S1>/Unit Delay4
  always @(posedge g_clk)
    begin : Unit_Delay4_process
      if (Rst_n == 1'b0) begin
        Unit_Delay4_out1 <= 1'b0;
      end
      else begin
        Unit_Delay4_out1 <= Switch1_out1;
      end
    end



  // <S1>/Or2
  assign Or2_out1 = Filter_Reset | Unit_Delay4_out1;



  // <S1>/Unit Delay6
  always @(posedge g_clk)
    begin : Unit_Delay6_process
      if (Rst_n == 1'b0) begin
        Unit_Delay6_out1 <= 1'b0;
      end
      else begin
        Unit_Delay6_out1 <= Switch5_out1;
      end
    end



  // <S1>/Switch5
  // 
  // <S1>/Goto1
  // 
  // <S1>/From3
  assign Switch5_out1 = (CT1_out1 == 1'b0 ? Unit_Delay6_out1 :
              Or2_out1);



  // <S1>/CT207
  assign CT207_out1 = Unit_Delay43_out1 == 4'b0000;



  // <S1>/Switch308
  assign Switch308_out1 = (Pulse_4096Hz == 1'b0 ? Unit_Delay121_out1 :
              1'b1);



  // <S1>/Switch307
  assign Switch307_out1 = (CT207_out1 == 1'b0 ? Switch308_out1 :
              1'b0);



  // <S1>/Unit Delay121
  always @(posedge g_clk)
    begin : Unit_Delay121_process
      if (Rst_n == 1'b0) begin
        Unit_Delay121_out1 <= 1'b0;
      end
      else begin
        Unit_Delay121_out1 <= Switch307_out1;
      end
    end



  // <S1>/Or1
  assign Or1_out1 = Pulse_4096Hz | Unit_Delay121_out1;



  // <S1>/Unit Delay122
  always @(posedge g_clk)
    begin : Unit_Delay122_process
      if (Rst_n == 1'b0) begin
        Unit_Delay122_out1 <= 1'b0;
      end
      else begin
        Unit_Delay122_out1 <= Switch309_out1;
      end
    end



  // <S1>/Switch309
  // 
  // <S1>/Goto264
  // 
  // <S1>/From4
  assign Switch309_out1 = (CT207_out1 == 1'b0 ? Unit_Delay122_out1 :
              Or1_out1);



  // <S1>/CT2
  assign CT2_out1 = Unit_Delay43_out1 == 4'b0001;



  // <S1>/CT4
  assign CT4_out1 = Unit_Delay43_out1 == 4'b0010;



  // <S1>/CT3
  assign CT3_out1 = Unit_Delay43_out1 == 4'b0011;



  // <S1>/CT8
  assign CT8_out1 = Unit_Delay43_out1 == 4'b0100;



  // <S1>/CT5
  assign CT5_out1 = Unit_Delay43_out1 == 4'b0101;



  // <S1>/CT7
  assign CT7_out1 = Unit_Delay43_out1 == 4'b0110;



  // <S1>/CT6
  assign CT6_out1 = Unit_Delay43_out1 == 4'b0111;



  // <S1>/CT13
  assign CT13_out1 = Unit_Delay43_out1 == 4'b1000;



  // <S1>/CT9
  assign CT9_out1 = Unit_Delay43_out1 == 4'b1001;



  // <S1>/CT12
  assign CT12_out1 = Unit_Delay43_out1 == 4'b1010;



  // <S1>/CT11
  assign CT11_out1 = Unit_Delay43_out1 == 4'b1011;



  // <S1>/CT17
  assign CT17_out1 = Unit_Delay43_out1 == 4'b1100;



  // <S1>/CT14
  assign CT14_out1 = Unit_Delay43_out1 == 4'b1101;



  // <S1>/CT16
  assign CT16_out1 = Unit_Delay43_out1 == 4'b1110;



  // <S1>/CT15
  assign CT15_out1 = Unit_Delay43_out1 == 4'b1111;



  // <S1>/Switch38
  // 
  // <S1>/Switch38
  // 
  // <S1>/Switch38
  assign signal1 = (CT15_out1 == 1'b0 ? In15 :
              In15);



  // <S1>/Switch50
  assign s = signal1;

  // <S1>/Switch50
  // 
  // <S1>/Switch50
  // 
  // <S1>/Switch50
  assign signal1_1 = (CT16_out1 == 1'b0 ? s :
              In14);



  // <S1>/Switch45
  assign s_1 = signal1_1;

  // <S1>/Switch45
  // 
  // <S1>/Switch45
  // 
  // <S1>/Switch45
  assign signal1_2 = (CT14_out1 == 1'b0 ? s_1 :
              In13);



  // <S1>/Switch41
  assign s_2 = signal1_2;

  // <S1>/Switch41
  // 
  // <S1>/Switch41
  // 
  // <S1>/Switch41
  assign signal1_3 = (CT17_out1 == 1'b0 ? s_2 :
              In12);



  // <S1>/Switch33
  assign s_3 = signal1_3;

  // <S1>/Switch33
  // 
  // <S1>/Switch33
  // 
  // <S1>/Switch33
  assign signal1_4 = (CT11_out1 == 1'b0 ? s_3 :
              In11);



  // <S1>/Switch57
  assign s_4 = signal1_4;

  // <S1>/Switch57
  // 
  // <S1>/Switch57
  // 
  // <S1>/Switch57
  assign signal1_5 = (CT12_out1 == 1'b0 ? s_4 :
              In10);



  // <S1>/Switch54
  assign s_5 = signal1_5;

  // <S1>/Switch54
  // 
  // <S1>/Switch54
  // 
  // <S1>/Switch54
  assign signal1_6 = (CT9_out1 == 1'b0 ? s_5 :
              In9);



  // <S1>/Switch51
  assign s_6 = signal1_6;

  // <S1>/Switch51
  // 
  // <S1>/Switch51
  // 
  // <S1>/Switch51
  assign signal1_7 = (CT13_out1 == 1'b0 ? s_6 :
              In8);



  // <S1>/Switch17
  assign s_7 = signal1_7;

  // <S1>/Switch17
  // 
  // <S1>/Switch17
  // 
  // <S1>/Switch17
  assign signal1_8 = (CT6_out1 == 1'b0 ? s_7 :
              In7);



  // <S1>/Switch26
  assign s_8 = signal1_8;

  // <S1>/Switch26
  // 
  // <S1>/Switch26
  // 
  // <S1>/Switch26
  assign signal1_9 = (CT7_out1 == 1'b0 ? s_8 :
              In6);



  // <S1>/Switch23
  assign s_9 = signal1_9;

  // <S1>/Switch23
  // 
  // <S1>/Switch23
  // 
  // <S1>/Switch23
  assign signal1_10 = (CT5_out1 == 1'b0 ? s_9 :
              In5);



  // <S1>/Switch20
  assign s_10 = signal1_10;

  // <S1>/Switch20
  // 
  // <S1>/Switch20
  // 
  // <S1>/Switch20
  assign signal1_11 = (CT8_out1 == 1'b0 ? s_10 :
              In4);



  // <S1>/Switch12
  assign s_11 = signal1_11;

  // <S1>/Switch12
  // 
  // <S1>/Switch12
  // 
  // <S1>/Switch12
  assign signal1_12 = (CT3_out1 == 1'b0 ? s_11 :
              In3);



  // <S1>/Switch9
  assign s_12 = signal1_12;

  // <S1>/Switch9
  // 
  // <S1>/Switch9
  // 
  // <S1>/Switch9
  assign signal1_13 = (CT4_out1 == 1'b0 ? s_12 :
              In2);



  // <S1>/Switch6
  assign s_13 = signal1_13;

  // <S1>/Switch6
  // 
  // <S1>/Switch6
  // 
  // <S1>/Switch6
  assign signal1_14 = (CT2_out1 == 1'b0 ? s_13 :
              In1);



  // <S1>/Switch44
  assign s_14 = signal1_14;

  // <S1>/Switch44
  // 
  // <S1>/Switch44
  // 
  // <S1>/Switch44
  // 
  // <S1>/Goto2
  // 
  // <S1>/Fro
  assign signal1_15 = (CT41_out1 == 1'b0 ? s_14 :
              In0);



  // <S1>/Bus Selector2
  // 
  // <S1>/Goto3
  assign signal1_16 = signal1_15;

  // <S1>/From1
  assign signal1_17 = signal1_16;

  // <S1>/Switch58
  assign Switch58_out1 = (signal1_17 == 1'b0 ? 8'sb11111111 :
              8'sb00000001);



  // <S1>/Switch3
  assign Switch3_out1 = (Switch309_out1 == 1'b0 ? 8'sb00000000 :
              Switch58_out1);



  // <S1>/Switch46
  assign Switch46_out1 = (CT41_out1 == 1'b0 ? Unit_Delay22_out1 :
              Switch27_out1);



  // <S1>/Unit Delay22
  always @(posedge g_clk)
    begin : Unit_Delay22_process
      if (Rst_n == 1'b0) begin
        Unit_Delay22_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay22_out1 <= Switch46_out1;
      end
    end



  assign Bus_Creator12_out1_signal2 = Unit_Delay22_out1;

  // <S1>/Switch7
  assign Switch7_out1 = (CT2_out1 == 1'b0 ? Unit_Delay1_out1 :
              Switch27_out1);



  // <S1>/Unit Delay1
  always @(posedge g_clk)
    begin : Unit_Delay1_process
      if (Rst_n == 1'b0) begin
        Unit_Delay1_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay1_out1 <= Switch7_out1;
      end
    end



  assign Bus_Creator1_out1_signal2 = Unit_Delay1_out1;

  // <S1>/Switch10
  assign Switch10_out1 = (CT4_out1 == 1'b0 ? Unit_Delay7_out1 :
              Switch27_out1);



  // <S1>/Unit Delay7
  always @(posedge g_clk)
    begin : Unit_Delay7_process
      if (Rst_n == 1'b0) begin
        Unit_Delay7_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay7_out1 <= Switch10_out1;
      end
    end



  // <S1>/Switch13
  assign Switch13_out1 = (CT3_out1 == 1'b0 ? Unit_Delay3_out1 :
              Switch27_out1);



  // <S1>/Unit Delay3
  always @(posedge g_clk)
    begin : Unit_Delay3_process
      if (Rst_n == 1'b0) begin
        Unit_Delay3_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay3_out1 <= Switch13_out1;
      end
    end



  assign Bus_Creator2_out1_signal2 = Unit_Delay3_out1;

  // <S1>/Switch21
  assign Switch21_out1 = (CT8_out1 == 1'b0 ? Unit_Delay11_out1 :
              Switch27_out1);



  // <S1>/Unit Delay11
  always @(posedge g_clk)
    begin : Unit_Delay11_process
      if (Rst_n == 1'b0) begin
        Unit_Delay11_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay11_out1 <= Switch21_out1;
      end
    end



  assign Bus_Creator5_out1_signal2 = Unit_Delay11_out1;

  // <S1>/Switch24
  assign Switch24_out1 = (CT5_out1 == 1'b0 ? Unit_Delay9_out1 :
              Switch27_out1);



  // <S1>/Unit Delay9
  // 
  // <S1>/Goto10
  // 
  // <S1>/From755
  // 
  // <S1>/Goto7
  // 
  // <S1>/From6
  // 
  // <S1>/Bus Creator1
  // 
  // <S1>/Bus Creator10
  // 
  // <S1>/Bus Creator11
  // 
  // <S1>/Bus Creator12
  // 
  // <S1>/Bus Creator13
  // 
  // <S1>/Bus Creator14
  // 
  // <S1>/Bus Creator15
  // 
  // <S1>/Bus Creator16
  // 
  // <S1>/Bus Creator2
  // 
  // <S1>/Bus Creator3
  // 
  // <S1>/Bus Creator4
  // 
  // <S1>/Bus Creator5
  // 
  // <S1>/Bus Creator6
  // 
  // <S1>/Bus Creator7
  // 
  // <S1>/Bus Creator8
  // 
  // <S1>/Bus Creator9
  // 
  // <S1>/Switch12
  // 
  // <S1>/Switch17
  // 
  // <S1>/Switch20
  // 
  // <S1>/Switch23
  // 
  // <S1>/Switch26
  // 
  // <S1>/Switch33
  // 
  // <S1>/Switch38
  // 
  // <S1>/Switch41
  // 
  // <S1>/Switch44
  // 
  // <S1>/Switch45
  // 
  // <S1>/Switch50
  // 
  // <S1>/Switch51
  // 
  // <S1>/Switch54
  // 
  // <S1>/Switch57
  // 
  // <S1>/Switch6
  // 
  // <S1>/Switch9
  // 
  // <S1>/Bus Creator15
  // 
  // <S1>/Switch38
  always @(posedge g_clk)
    begin : Unit_Delay9_process
      if (Rst_n == 1'b0) begin
        Unit_Delay9_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay9_out1 <= Switch24_out1;
      end
    end



  assign Bus_Creator4_out1_signal2 = Unit_Delay9_out1;

  // <S1>/Switch15
  assign Switch15_out1 = (CT7_out1 == 1'b0 ? Unit_Delay15_out1 :
              Switch27_out1);



  // <S1>/Unit Delay15
  always @(posedge g_clk)
    begin : Unit_Delay15_process
      if (Rst_n == 1'b0) begin
        Unit_Delay15_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay15_out1 <= Switch15_out1;
      end
    end



  assign Bus_Creator7_out1_signal2 = Unit_Delay15_out1;

  // <S1>/Switch18
  assign Switch18_out1 = (CT6_out1 == 1'b0 ? Unit_Delay13_out1 :
              Switch27_out1);



  // <S1>/Unit Delay13
  always @(posedge g_clk)
    begin : Unit_Delay13_process
      if (Rst_n == 1'b0) begin
        Unit_Delay13_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay13_out1 <= Switch18_out1;
      end
    end



  assign Bus_Creator6_out1_signal2 = Unit_Delay13_out1;

  // <S1>/Switch52
  assign Switch52_out1 = (CT13_out1 == 1'b0 ? Unit_Delay28_out1 :
              Switch27_out1);



  // <S1>/Unit Delay28
  always @(posedge g_clk)
    begin : Unit_Delay28_process
      if (Rst_n == 1'b0) begin
        Unit_Delay28_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay28_out1 <= Switch52_out1;
      end
    end



  assign Bus_Creator9_out1_signal2 = Unit_Delay28_out1;

  // <S1>/Switch55
  assign Switch55_out1 = (CT9_out1 == 1'b0 ? Unit_Delay17_out1 :
              Switch27_out1);



  // <S1>/Unit Delay17
  always @(posedge g_clk)
    begin : Unit_Delay17_process
      if (Rst_n == 1'b0) begin
        Unit_Delay17_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay17_out1 <= Switch55_out1;
      end
    end



  assign Bus_Creator8_out1_signal2 = Unit_Delay17_out1;

  // <S1>/Switch31
  assign Switch31_out1 = (CT12_out1 == 1'b0 ? Unit_Delay32_out1 :
              Switch27_out1);



  // <S1>/Unit Delay32
  always @(posedge g_clk)
    begin : Unit_Delay32_process
      if (Rst_n == 1'b0) begin
        Unit_Delay32_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay32_out1 <= Switch31_out1;
      end
    end



  assign Bus_Creator11_out1_signal2 = Unit_Delay32_out1;

  // <S1>/Switch34
  assign Switch34_out1 = (CT11_out1 == 1'b0 ? Unit_Delay30_out1 :
              Switch27_out1);



  // <S1>/Unit Delay30
  always @(posedge g_clk)
    begin : Unit_Delay30_process
      if (Rst_n == 1'b0) begin
        Unit_Delay30_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay30_out1 <= Switch34_out1;
      end
    end



  assign Bus_Creator10_out1_signal2 = Unit_Delay30_out1;

  // <S1>/Switch42
  assign Switch42_out1 = (CT17_out1 == 1'b0 ? Unit_Delay19_out1 :
              Switch27_out1);



  // <S1>/Unit Delay19
  always @(posedge g_clk)
    begin : Unit_Delay19_process
      if (Rst_n == 1'b0) begin
        Unit_Delay19_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay19_out1 <= Switch42_out1;
      end
    end



  assign Bus_Creator14_out1_signal2 = Unit_Delay19_out1;

  // <S1>/Switch48
  assign Switch48_out1 = (CT14_out1 == 1'b0 ? Unit_Delay34_out1 :
              Switch27_out1);



  // <S1>/Unit Delay34
  always @(posedge g_clk)
    begin : Unit_Delay34_process
      if (Rst_n == 1'b0) begin
        Unit_Delay34_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay34_out1 <= Switch48_out1;
      end
    end



  assign Bus_Creator13_out1_signal2 = Unit_Delay34_out1;

  // <S1>/Switch36
  assign Switch36_out1 = (CT16_out1 == 1'b0 ? Unit_Delay25_out1 :
              Switch27_out1);



  // <S1>/Unit Delay25
  always @(posedge g_clk)
    begin : Unit_Delay25_process
      if (Rst_n == 1'b0) begin
        Unit_Delay25_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay25_out1 <= Switch36_out1;
      end
    end



  assign Bus_Creator16_out1_signal2 = Unit_Delay25_out1;

  // <S1>/Switch28
  assign Switch28_out1 = (CT10_out1 == 1'b0 ? Switch2_out1 :
              8'sb00000000);



  // <S1>/Dy2
  //assign Dy2_relop1 = Switch28_out1 >= 8'sb00010100;
  assign Dy2_relop1 = Switch28_out1 >= 8'sb00101000;



  // <S1>/Switch27
  // 
  // <S1>/Goto25
  // 
  // <S1>/From12
  // 
  // <S1>/Goto25
  // 
  // <S1>/From9
  // 
  // <S1>/Goto25
  // 
  // <S1>/From50
  // 
  // <S1>/Goto25
  // 
  // <S1>/From47
  // 
  // <S1>/Goto25
  // 
  // <S1>/From44
  // 
  // <S1>/Goto25
  // 
  // <S1>/From40
  // 
  // <S1>/Goto25
  // 
  // <S1>/From38
  // 
  // <S1>/Goto25
  // 
  // <S1>/From37
  // 
  // <S1>/Goto25
  // 
  // <S1>/From30
  // 
  // <S1>/Goto25
  // 
  // <S1>/From29
  // 
  // <S1>/Goto25
  // 
  // <S1>/From26
  // 
  // <S1>/Goto25
  // 
  // <S1>/From23
  // 
  // <S1>/Goto25
  // 
  // <S1>/From2
  // 
  // <S1>/Goto25
  // 
  // <S1>/From18
  // 
  // <S1>/Goto25
  // 
  // <S1>/From17
  // 
  // <S1>/Goto25
  // 
  // <S1>/From122
  //assign Switch27_out1 = (Dy2_relop1 == 1'b0 ? Switch28_out1 :
  //            8'sb00010100);
  assign Switch27_out1 = (Dy2_relop1 == 1'b0 ? Switch28_out1 :
              8'sb00101000);


  // <S1>/Switch39
  assign Switch39_out1 = (CT15_out1 == 1'b0 ? Unit_Delay21_out1 :
              Switch27_out1);



  // <S1>/Unit Delay21
  always @(posedge g_clk)
    begin : Unit_Delay21_process
      if (Rst_n == 1'b0) begin
        Unit_Delay21_out1 <= 8'sb00000000;
      end
      else begin
        Unit_Delay21_out1 <= Switch39_out1;
      end
    end



  // <S1>/Switch38
  assign signal2 = (CT15_out1 == 1'b0 ? Unit_Delay21_out1 :
              Unit_Delay21_out1);



  assign s_15 = signal2;

  // <S1>/Switch50
  assign signal2_1 = (CT16_out1 == 1'b0 ? s_15 :
              Bus_Creator16_out1_signal2);



  assign s_16 = signal2_1;

  // <S1>/Switch45
  assign signal2_2 = (CT14_out1 == 1'b0 ? s_16 :
              Bus_Creator13_out1_signal2);



  assign s_17 = signal2_2;

  // <S1>/Switch41
  assign signal2_3 = (CT17_out1 == 1'b0 ? s_17 :
              Bus_Creator14_out1_signal2);



  assign s_18 = signal2_3;

  // <S1>/Switch33
  assign signal2_4 = (CT11_out1 == 1'b0 ? s_18 :
              Bus_Creator10_out1_signal2);



  assign s_19 = signal2_4;

  // <S1>/Switch57
  assign signal2_5 = (CT12_out1 == 1'b0 ? s_19 :
              Bus_Creator11_out1_signal2);



  assign s_20 = signal2_5;

  // <S1>/Switch54
  assign signal2_6 = (CT9_out1 == 1'b0 ? s_20 :
              Bus_Creator8_out1_signal2);



  assign s_21 = signal2_6;

  // <S1>/Switch51
  assign signal2_7 = (CT13_out1 == 1'b0 ? s_21 :
              Bus_Creator9_out1_signal2);



  assign s_22 = signal2_7;

  // <S1>/Switch17
  assign signal2_8 = (CT6_out1 == 1'b0 ? s_22 :
              Bus_Creator6_out1_signal2);



  assign s_23 = signal2_8;

  // <S1>/Switch26
  assign signal2_9 = (CT7_out1 == 1'b0 ? s_23 :
              Bus_Creator7_out1_signal2);



  assign s_24 = signal2_9;

  // <S1>/Switch23
  assign signal2_10 = (CT5_out1 == 1'b0 ? s_24 :
              Bus_Creator4_out1_signal2);



  assign s_25 = signal2_10;

  // <S1>/Switch20
  assign signal2_11 = (CT8_out1 == 1'b0 ? s_25 :
              Bus_Creator5_out1_signal2);



  assign s_26 = signal2_11;

  // <S1>/Switch12
  assign signal2_12 = (CT3_out1 == 1'b0 ? s_26 :
              Bus_Creator2_out1_signal2);



  assign s_27 = signal2_12;

  // <S1>/Switch9
  assign signal2_13 = (CT4_out1 == 1'b0 ? s_27 :
              Unit_Delay7_out1);



  assign s_28 = signal2_13;

  // <S1>/Switch6
  assign signal2_14 = (CT2_out1 == 1'b0 ? s_28 :
              Bus_Creator1_out1_signal2);



  assign s_29 = signal2_14;

  // <S1>/Switch44
  assign signal2_15 = (CT41_out1 == 1'b0 ? s_29 :
              Bus_Creator12_out1_signal2);



  // <S1>/Goto4
  assign signal2_16 = signal2_15;

  // <S1>/From109
  assign signal2_17 = signal2_16;

  // <S1>/Add3
  assign Add3_out1 = Switch3_out1 + signal2_17;



  // <S1>/Switch2
  assign Switch2_out1 = (Switch5_out1 == 1'b0 ? Add3_out1 :
              8'sb11111111);



  // <S1>/CT10
  assign CT10_out1 = Switch2_out1 <= 8'sb00000000;



  assign Bus_Creator12_out1_signal3 = Unit_Delay23_out1;

  // <S1>/Switch8
  assign Switch8_out1 = (CT2_out1 == 1'b0 ? Unit_Delay2_out1 :
              Switch30_out1);



  // <S1>/Unit Delay2
  always @(posedge g_clk)
    begin : Unit_Delay2_process
      if (Rst_n == 1'b0) begin
        Unit_Delay2_out1 <= 1'b0;
      end
      else begin
        Unit_Delay2_out1 <= Switch8_out1;
      end
    end



  assign Bus_Creator1_out1_signal3 = Unit_Delay2_out1;

  // <S1>/Switch11
  assign Switch11_out1 = (CT4_out1 == 1'b0 ? Unit_Delay8_out1 :
              Switch30_out1);



  // <S1>/Unit Delay8
  always @(posedge g_clk)
    begin : Unit_Delay8_process
      if (Rst_n == 1'b0) begin
        Unit_Delay8_out1 <= 1'b0;
      end
      else begin
        Unit_Delay8_out1 <= Switch11_out1;
      end
    end



  // <S1>/Switch14
  assign Switch14_out1 = (CT3_out1 == 1'b0 ? Unit_Delay5_out1 :
              Switch30_out1);



  // <S1>/Unit Delay5
  always @(posedge g_clk)
    begin : Unit_Delay5_process
      if (Rst_n == 1'b0) begin
        Unit_Delay5_out1 <= 1'b0;
      end
      else begin
        Unit_Delay5_out1 <= Switch14_out1;
      end
    end



  assign Bus_Creator2_out1_signal3 = Unit_Delay5_out1;

  // <S1>/Switch22
  assign Switch22_out1 = (CT8_out1 == 1'b0 ? Unit_Delay12_out1 :
              Switch30_out1);



  // <S1>/Unit Delay12
  always @(posedge g_clk)
    begin : Unit_Delay12_process
      if (Rst_n == 1'b0) begin
        Unit_Delay12_out1 <= 1'b0;
      end
      else begin
        Unit_Delay12_out1 <= Switch22_out1;
      end
    end



  assign Bus_Creator5_out1_signal3 = Unit_Delay12_out1;

  // <S1>/Switch25
  assign Switch25_out1 = (CT5_out1 == 1'b0 ? Unit_Delay10_out1 :
              Switch30_out1);



  // <S1>/Unit Delay10
  always @(posedge g_clk)
    begin : Unit_Delay10_process
      if (Rst_n == 1'b0) begin
        Unit_Delay10_out1 <= 1'b0;
      end
      else begin
        Unit_Delay10_out1 <= Switch25_out1;
      end
    end



  assign Bus_Creator4_out1_signal3 = Unit_Delay10_out1;

  // <S1>/Switch16
  assign Switch16_out1 = (CT7_out1 == 1'b0 ? Unit_Delay16_out1 :
              Switch30_out1);



  // <S1>/Unit Delay16
  always @(posedge g_clk)
    begin : Unit_Delay16_process
      if (Rst_n == 1'b0) begin
        Unit_Delay16_out1 <= 1'b0;
      end
      else begin
        Unit_Delay16_out1 <= Switch16_out1;
      end
    end



  assign Bus_Creator7_out1_signal3 = Unit_Delay16_out1;

  // <S1>/Switch19
  assign Switch19_out1 = (CT6_out1 == 1'b0 ? Unit_Delay14_out1 :
              Switch30_out1);



  // <S1>/Unit Delay14
  always @(posedge g_clk)
    begin : Unit_Delay14_process
      if (Rst_n == 1'b0) begin
        Unit_Delay14_out1 <= 1'b0;
      end
      else begin
        Unit_Delay14_out1 <= Switch19_out1;
      end
    end



  assign Bus_Creator6_out1_signal3 = Unit_Delay14_out1;

  // <S1>/Switch53
  assign Switch53_out1 = (CT13_out1 == 1'b0 ? Unit_Delay29_out1 :
              Switch30_out1);



  // <S1>/Unit Delay29
  always @(posedge g_clk)
    begin : Unit_Delay29_process
      if (Rst_n == 1'b0) begin
        Unit_Delay29_out1 <= 1'b0;
      end
      else begin
        Unit_Delay29_out1 <= Switch53_out1;
      end
    end



  assign Bus_Creator9_out1_signal3 = Unit_Delay29_out1;

  // <S1>/Switch56
  assign Switch56_out1 = (CT9_out1 == 1'b0 ? Unit_Delay27_out1 :
              Switch30_out1);



  // <S1>/Unit Delay27
  always @(posedge g_clk)
    begin : Unit_Delay27_process
      if (Rst_n == 1'b0) begin
        Unit_Delay27_out1 <= 1'b0;
      end
      else begin
        Unit_Delay27_out1 <= Switch56_out1;
      end
    end



  assign Bus_Creator8_out1_signal3 = Unit_Delay27_out1;

  // <S1>/Switch32
  assign Switch32_out1 = (CT12_out1 == 1'b0 ? Unit_Delay33_out1 :
              Switch30_out1);



  // <S1>/Unit Delay33
  always @(posedge g_clk)
    begin : Unit_Delay33_process
      if (Rst_n == 1'b0) begin
        Unit_Delay33_out1 <= 1'b0;
      end
      else begin
        Unit_Delay33_out1 <= Switch32_out1;
      end
    end



  assign Bus_Creator11_out1_signal3 = Unit_Delay33_out1;

  // <S1>/Switch35
  assign Switch35_out1 = (CT11_out1 == 1'b0 ? Unit_Delay31_out1 :
              Switch30_out1);



  // <S1>/Unit Delay31
  always @(posedge g_clk)
    begin : Unit_Delay31_process
      if (Rst_n == 1'b0) begin
        Unit_Delay31_out1 <= 1'b0;
      end
      else begin
        Unit_Delay31_out1 <= Switch35_out1;
      end
    end



  assign Bus_Creator10_out1_signal3 = Unit_Delay31_out1;

  // <S1>/Switch43
  assign Switch43_out1 = (CT17_out1 == 1'b0 ? Unit_Delay20_out1 :
              Switch30_out1);



  // <S1>/Unit Delay20
  always @(posedge g_clk)
    begin : Unit_Delay20_process
      if (Rst_n == 1'b0) begin
        Unit_Delay20_out1 <= 1'b0;
      end
      else begin
        Unit_Delay20_out1 <= Switch43_out1;
      end
    end



  assign Bus_Creator14_out1_signal3 = Unit_Delay20_out1;

  // <S1>/Switch49
  assign Switch49_out1 = (CT14_out1 == 1'b0 ? Unit_Delay18_out1 :
              Switch30_out1);



  // <S1>/Unit Delay18
  always @(posedge g_clk)
    begin : Unit_Delay18_process
      if (Rst_n == 1'b0) begin
        Unit_Delay18_out1 <= 1'b0;
      end
      else begin
        Unit_Delay18_out1 <= Switch49_out1;
      end
    end



  assign Bus_Creator13_out1_signal3 = Unit_Delay18_out1;

  // <S1>/Switch37
  assign Switch37_out1 = (CT16_out1 == 1'b0 ? Unit_Delay26_out1 :
              Switch30_out1);



  // <S1>/Unit Delay26
  always @(posedge g_clk)
    begin : Unit_Delay26_process
      if (Rst_n == 1'b0) begin
        Unit_Delay26_out1 <= 1'b0;
      end
      else begin
        Unit_Delay26_out1 <= Switch37_out1;
      end
    end



  assign Bus_Creator16_out1_signal3 = Unit_Delay26_out1;

  // <S1>/Switch40
  assign Switch40_out1 = (CT15_out1 == 1'b0 ? Unit_Delay24_out1 :
              Switch30_out1);



  // <S1>/Unit Delay24
  always @(posedge g_clk)
    begin : Unit_Delay24_process
      if (Rst_n == 1'b0) begin
        Unit_Delay24_out1 <= 1'b0;
      end
      else begin
        Unit_Delay24_out1 <= Switch40_out1;
      end
    end



  // <S1>/Switch38
  assign signal3 = (CT15_out1 == 1'b0 ? Unit_Delay24_out1 :
              Unit_Delay24_out1);



  assign s_30 = signal3;

  // <S1>/Switch50
  assign signal3_1 = (CT16_out1 == 1'b0 ? s_30 :
              Bus_Creator16_out1_signal3);



  assign s_31 = signal3_1;

  // <S1>/Switch45
  assign signal3_2 = (CT14_out1 == 1'b0 ? s_31 :
              Bus_Creator13_out1_signal3);



  assign s_32 = signal3_2;

  // <S1>/Switch41
  assign signal3_3 = (CT17_out1 == 1'b0 ? s_32 :
              Bus_Creator14_out1_signal3);



  assign s_33 = signal3_3;

  // <S1>/Switch33
  assign signal3_4 = (CT11_out1 == 1'b0 ? s_33 :
              Bus_Creator10_out1_signal3);



  assign s_34 = signal3_4;

  // <S1>/Switch57
  assign signal3_5 = (CT12_out1 == 1'b0 ? s_34 :
              Bus_Creator11_out1_signal3);



  assign s_35 = signal3_5;

  // <S1>/Switch54
  assign signal3_6 = (CT9_out1 == 1'b0 ? s_35 :
              Bus_Creator8_out1_signal3);



  assign s_36 = signal3_6;

  // <S1>/Switch51
  assign signal3_7 = (CT13_out1 == 1'b0 ? s_36 :
              Bus_Creator9_out1_signal3);



  assign s_37 = signal3_7;

  // <S1>/Switch17
  assign signal3_8 = (CT6_out1 == 1'b0 ? s_37 :
              Bus_Creator6_out1_signal3);



  assign s_38 = signal3_8;

  // <S1>/Switch26
  assign signal3_9 = (CT7_out1 == 1'b0 ? s_38 :
              Bus_Creator7_out1_signal3);



  assign s_39 = signal3_9;

  // <S1>/Switch23
  assign signal3_10 = (CT5_out1 == 1'b0 ? s_39 :
              Bus_Creator4_out1_signal3);



  assign s_40 = signal3_10;

  // <S1>/Switch20
  assign signal3_11 = (CT8_out1 == 1'b0 ? s_40 :
              Bus_Creator5_out1_signal3);



  assign s_41 = signal3_11;

  // <S1>/Switch12
  assign signal3_12 = (CT3_out1 == 1'b0 ? s_41 :
              Bus_Creator2_out1_signal3);



  assign s_42 = signal3_12;

  // <S1>/Switch9
  assign signal3_13 = (CT4_out1 == 1'b0 ? s_42 :
              Unit_Delay8_out1);



  assign s_43 = signal3_13;

  // <S1>/Switch6
  assign signal3_14 = (CT2_out1 == 1'b0 ? s_43 :
              Bus_Creator1_out1_signal3);



  assign s_44 = signal3_14;

  // <S1>/Switch44
  assign signal3_15 = (CT41_out1 == 1'b0 ? s_44 :
              Bus_Creator12_out1_signal3);



  // <S1>/Goto5
  assign signal3_16 = signal3_15;

  // <S1>/From133
  assign signal3_17 = signal3_16;

  // <S1>/Switch29
  assign Switch29_out1 = (Dy2_relop1 == 1'b0 ? signal3_17 :
              1'b1);



  // <S1>/Switch30
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From11
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From124
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From14
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From16
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From20
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From22
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From25
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From28
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From32
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From34
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From36
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From41
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From43
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From46
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From49
  // 
  // <S1>/Data Type Conversion
  // 
  // <S1>/Goto40
  // 
  // <S1>/From8
  assign Switch30_out1 = (CT10_out1 == 1'b0 ? Switch29_out1 :
              1'b0);



  // <S1>/Switch47
  assign Switch47_out1 = (CT41_out1 == 1'b0 ? Unit_Delay23_out1 :
              Switch30_out1);



  // <S1>/Unit Delay23
  always @(posedge g_clk)
    begin : Unit_Delay23_process
      if (Rst_n == 1'b0) begin
        Unit_Delay23_out1 <= 1'b0;
      end
      else begin
        Unit_Delay23_out1 <= Switch47_out1;
      end
    end



  assign BitFltedOut0 = Unit_Delay23_out1;

  assign BitFltedOut1 = Unit_Delay2_out1;

  assign BitFltedOut2 = Unit_Delay8_out1;

  assign BitFltedOut3 = Unit_Delay5_out1;

  assign BitFltedOut4 = Unit_Delay12_out1;

  assign BitFltedOut5 = Unit_Delay10_out1;

  assign BitFltedOut6 = Unit_Delay16_out1;

  assign BitFltedOut7 = Unit_Delay14_out1;

  assign BitFltedOut8 = Unit_Delay29_out1;

  assign BitFltedOut9 = Unit_Delay27_out1;

  assign BitFltedOut10 = Unit_Delay33_out1;

  assign BitFltedOut11 = Unit_Delay31_out1;

  assign BitFltedOut12 = Unit_Delay20_out1;

  assign BitFltedOut13 = Unit_Delay18_out1;

  assign BitFltedOut14 = Unit_Delay26_out1;

  assign BitFltedOut15 = Unit_Delay24_out1;

endmodule  // BitFilter_V11

