// -------------------------------------------------------------
// 
// File Name: Work_Comm_Handle_V13c\Comm_Handle_V13c\Case1.v
// Created: 2020-08-03 15:57:41
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Case1
// Source Path: Comm_Handle_V13c/FIFO_SEL_V10/Case1
// Hierarchy Level: 1
// 
// ------------------------------------------------------------- 
`timescale 1 ns / 1 ns 
module FifoSelZ ( 
		   input Soft_on,
			 input PhaseInv,
		   input [11:0] Ia_CT_FltP32,
		   input [11:0] Idp_C_b12,
		   input [15:0] Pload_b16,
		   input [11:0] Ia_CT,
		   wire [11:0] Ib_CT,
		   input [11:0] Ic_CT,			 
		   input [11:0] sinA,
		   input [11:0] sinB,
		   input [11:0] sinC,
		   input rdakn,
		   input HvrtFlg,
		   input LvrtFlg,
		   //====================================================
		   input [3:0]  FIFO_ID,
		   input [15:0] FIFOX_DATA_SEL, 
           input [11:0] Uab_b12,
           input [11:0] Ubc_b12,
		   input [11:0] Uca_b12,
		   input [11:0] Udc_b12,
		   input [11:0] UposGnd_b12,
		   input [11:0] UnegGnd_b12,
		   input [11:0] Ubtr_b12, 
		   input [11:0] Ia_b12,
		   input [11:0] Ib_b12,
		   input [11:0] Ic_b12,
		   input [11:0] Idc_b12, 
		   input [11:0] Udp_b12,
		   input [11:0] Uqp_b12,
		   input [11:0] Udn_b12,
		   input [11:0] Uqn_b12,
		   input [11:0] Udp_ref_b12,
		   input [11:0] Uqp_ref_b12,
		   input [11:0] Udn_ref_b12,
		   input [11:0] Uqn_ref_b12,
		   input [11:0] Udp_PLL_b12,
		   input [11:0] Uqp_PLL_b12, 
		   input [11:0] Idp_b12,
		   input [11:0] Iqp_b12,
		   input [11:0] Idn_b12,
		   input [11:0] Iqn_b12,
		   input [11:0] Idp_ref_in_b12,
		   input [11:0] Iqp_ref_in_b12,
		   input [11:0] Idn_ref_in_b12,
		   input [11:0] Iqn_ref_in_b12, 
		   input [11:0] Mdp_b12, 
		   input [11:0] Mqp_b12,
		   input [11:0] Mdn_b12,
		   input [11:0] Mqn_b12,
		   input [11:0] Sinwt,
		   input [11:0] Coswt,
		   input [11:0] nSinwt,
		   input [11:0] nCoswt,
		   input [11:0] Ma_b12,
		   input [11:0] Mb_b12,
		   input [11:0] Mc_b12,
		   input [11:0] MaIn_b12,
		   input [11:0] MbIn_b12,
		   input [11:0] McIn_b12,
		   input [11:0] MsvA_b12,
		   input [11:0] MsvB_b12,
		   input [11:0] MsvC_b12,
		   input [15:0] debug0,
		   input [15:0] debug1,
		   input [15:0] debug2,
		   input [15:0] debug3,
		   input [15:0] debug4,
		   input [15:0] debug5,
		   input [15:0] debug6,
		   input [15:0] debug7,
		   input [15:0] debug8,
		   input [15:0] debug9, 
		   input [15:0] debug10,
		   input [15:0] debug11,
		   input [15:0] debug12,
		   input [15:0] debug13,
		   input [15:0] debug14,
		   input [15:0] debug15,
		   input [15:0] debug16,
		   input [15:0] debug17,
		   input [15:0] debug18,
		   input [15:0] debug19,
		   input [15:0] debug20,
		   input [15:0] debug21,
		   input [15:0] debug22,
		   input [15:0] debug23,
		   input [15:0] debug24,
		   input [15:0] debug25,
		   input [15:0] debug26,
		   input [15:0] debug27,
		   input [15:0] debug28,
		   input [15:0] debug29,
         output [15:0] FIFOX_Data_r
          ); 
  reg [15:0] FIFO_Data_r; 
  assign Ib_CT = -Ia_CT-Ic_CT;
  always@( * ) begin  
	case(FIFOX_DATA_SEL)  
		 //====================== ad input ==========================
		 16'd0: begin  //0最常用
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Uab_b12	[11]}},Uab_b12}; end //通道0
				4'd1: begin FIFO_Data_r[15:0] = {{4{Ubc_b12	[11]}},Ubc_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{Uca_b12	[11]}},Uca_b12}; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Ia_b12	[11]}},Ia_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Ib_b12	[11]}},Ib_b12}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Ic_b12	[11]}},Ic_b12}; end 
				4'd6: begin FIFO_Data_r[15:0] = {{4{Udc_b12	[11]}},Udc_b12}; end 
				4'd7: begin FIFO_Data_r[15:0] = {{4{Idc_b12	[11]}},Idc_b12}; end 
				4'd8: begin FIFO_Data_r[15:0] = {{4{Ubtr_b12[11]}},Ubtr_b12}; end //通道8
			endcase
		 end 
		16'd1: begin  //0较常用
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Udp_b12	[11]}},Udp_b12}; end 
				//4'd0: begin FIFO_Data_r[15:0] = rdakn ? 16'd1000 : 16'd0; end 
				4'd1: begin FIFO_Data_r[15:0] = {{4{Uqp_b12	[11]}},Uqp_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{Uqp_ref_b12	[11]}},Uqp_ref_b12}; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Udn_b12	[11]}},Udn_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Uqn_b12	[11]}},Uqn_b12}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Uqn_ref_b12	[11]}},Uqn_ref_b12}; end 
				4'd6: begin FIFO_Data_r[15:0] = {{4{UposGnd_b12	[11]}},UposGnd_b12}; end 
				4'd7: begin FIFO_Data_r[15:0] = {{4{UnegGnd_b12	[11]}},UnegGnd_b12}; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end 
		16'd2: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Idp_b12	[11]}},Idp_b12}; end 
				4'd1: begin FIFO_Data_r[15:0] = {{4{Iqp_b12	[11]}},Iqp_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{Iqp_ref_in_b12	[11]}},Iqp_ref_in_b12}; end  //++
				4'd3: begin FIFO_Data_r[15:0] = {{4{Idn_b12	[11]}},Idn_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Iqn_b12	[11]}},Iqn_b12}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Iqn_ref_in_b12	[11]}},Iqn_ref_in_b12}; end 
				4'd6: begin FIFO_Data_r[15:0] = HvrtFlg ? 1000 : 0; end 
				4'd7: begin FIFO_Data_r[15:0] = LvrtFlg ? 1000 : 0; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end 
		16'd3: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Ia_CT_FltP32	[11]}},Ia_CT_FltP32}; end 
				4'd1: begin FIFO_Data_r[15:0] = {{4{Idp_C_b12	[11]}},Idp_C_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = Pload_b16; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Ia_CT	[11]}},Ia_CT}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Ib_CT	[11]}},Ib_CT}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Ic_CT	[11]}},Ic_CT}; end 
				4'd6: begin FIFO_Data_r[15:0] = {{4{Iqp_b12	[11]}},Iqp_b12}; end 
				4'd7: begin FIFO_Data_r[15:0] = {{4{Iqn_b12	[11]}},Iqn_b12}; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end 
		16'd4: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Idp_ref_in_b12	[11]}},Idp_ref_in_b12}; end  //++
				4'd1: begin FIFO_Data_r[15:0] = {{4{Idp_b12	[11]}},Idp_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{Iqp_b12	[11]}},Iqp_b12}; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Udn_ref_b12	[11]}},Udn_ref_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Udn_b12	[11]}},Udn_b12}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Uqn_b12	[11]}},Uqn_b12}; end 
				4'd6: begin FIFO_Data_r[15:0] = PhaseInv ? 1000 : 0; end 
				4'd7: begin FIFO_Data_r[15:0] = Soft_on ? 16'b1000 : 0; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end		
		16'd5: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{MaIn_b12	[11]}},MaIn_b12}; end 
				4'd1: begin FIFO_Data_r[15:0] = {{4{MbIn_b12	[11]}},MbIn_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{McIn_b12	[11]}},McIn_b12}; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Ma_b12	[11]}},Ma_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Mb_b12	[11]}},Mb_b12}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Mc_b12	[11]}},Mc_b12}; end 
				4'd6: begin FIFO_Data_r[15:0] = {{4{MsvA_b12	[11]}},MsvA_b12}; end 
				4'd7: begin FIFO_Data_r[15:0] = {{4{MsvB_b12	[11]}},MsvB_b12}; end 
				4'd8: begin FIFO_Data_r[15:0] = {{4{MsvC_b12	[11]}},MsvC_b12}; end 
			endcase
		 end		 
		16'd6: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = {{4{Mdp_b12	[11]}},Mdp_b12}; end 
				4'd1: begin FIFO_Data_r[15:0] = {{4{Mqp_b12	[11]}},Mqp_b12}; end 
				4'd2: begin FIFO_Data_r[15:0] = {{4{Mdn_b12	[11]}},Mdn_b12}; end 
				4'd3: begin FIFO_Data_r[15:0] = {{4{Mqn_b12	[11]}},Mqn_b12}; end 
				4'd4: begin FIFO_Data_r[15:0] = {{4{Sinwt	[11]}},Sinwt}; end 
				4'd5: begin FIFO_Data_r[15:0] = {{4{Coswt	[11]}},Coswt}; end 
				4'd6: begin FIFO_Data_r[15:0] = {{4{nSinwt	[11]}},nSinwt}; end 
				4'd7: begin FIFO_Data_r[15:0] = {{4{nCoswt	[11]}},nCoswt}; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end
		16'd7: begin 
			case(FIFO_ID) 
				4'd0: begin FIFO_Data_r[15:0] = 16'b0; end  //++
				4'd1: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd2: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd3: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd4: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd5: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd6: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd7: begin FIFO_Data_r[15:0] = 16'b0; end 
				4'd8: begin FIFO_Data_r[15:0] = 16'b0; end 
			endcase
		 end
		 16'd100: begin FIFO_Data_r[15:0] = {{4{Uab_b12	[11]}},Uab_b12}; end 
		 16'd101: begin FIFO_Data_r[15:0] = {{4{Ubc_b12	[11]}},Ubc_b12}; end
		 16'd102: begin FIFO_Data_r[15:0] = {{4{Uca_b12	[11]}},Uca_b12}; end
		 16'd103: begin FIFO_Data_r[15:0] = {{4{Udc_b12	[11]}},Udc_b12}; end
		 16'd104: begin FIFO_Data_r[15:0] = {{4{UposGnd_b12	[11]}},UposGnd_b12}; end
		 16'd105: begin FIFO_Data_r[15:0] = {{4{UnegGnd_b12	[11]}},UnegGnd_b12}; end
		 16'd106: begin FIFO_Data_r[15:0] = {{4{Ubtr_b12	[11]}},Ubtr_b12}; end
		 16'd107: begin FIFO_Data_r[15:0] = 0; end //Ubtr2_b12
		 16'd108: begin FIFO_Data_r[15:0] = 0; end //Ubtr3_b12
		 16'd109: begin FIFO_Data_r[15:0] = 0; end //Ubtr4_b12
		 16'd120: begin FIFO_Data_r[15:0] = {{4{Ia_b12	[11]}},Ia_b12}; end
		 16'd121: begin FIFO_Data_r[15:0] = {{4{Ib_b12	[11]}},Ib_b12}; end
		 16'd122: begin FIFO_Data_r[15:0] = {{4{Ic_b12	[11]}},Ic_b12}; end
		 16'd123: begin FIFO_Data_r[15:0] = {{4{Idc_b12	[11]}},Idc_b12}; end
		 16'd124: begin FIFO_Data_r[15:0] = 0; end //Ibtr1_b12
		 16'd125: begin FIFO_Data_r[15:0] = 0; end //Ibtr2_b12
		 16'd126: begin FIFO_Data_r[15:0] = 0; end //Ibtr3_b12
		 16'd127: begin FIFO_Data_r[15:0] = 0; end //Ibtr4_b12
		 16'd128: begin FIFO_Data_r[15:0] = 0; end //Ipv1_b12
		 16'd129: begin FIFO_Data_r[15:0] = 0; end //Ipv2_b12
		 //====================== mea ==========================
		 16'd200: begin FIFO_Data_r[15:0] = {{4{Udp_b12	[11]}},Udp_b12}; end
		 16'd201: begin FIFO_Data_r[15:0] = {{4{Uqp_b12	[11]}},Uqp_b12}; end
		 16'd202: begin FIFO_Data_r[15:0] = {{4{Udn_b12	[11]}},Udn_b12}; end
		 16'd203: begin FIFO_Data_r[15:0] = {{4{Uqn_b12	[11]}},Uqn_b12}; end
		 16'd204: begin FIFO_Data_r[15:0] = {{4{Udp_ref_b12	[11]}},Udp_ref_b12}; end
		 16'd205: begin FIFO_Data_r[15:0] = {{4{Uqp_ref_b12	[11]}},Uqp_ref_b12}; end
		 16'd206: begin FIFO_Data_r[15:0] = {{4{Udn_ref_b12	[11]}},Udn_ref_b12}; end 
		 16'd207: begin FIFO_Data_r[15:0] = {{4{Uqn_ref_b12	[11]}},Uqn_ref_b12}; end
		 16'd208: begin FIFO_Data_r[15:0] = {{4{Udp_PLL_b12	[11]}},Udp_PLL_b12}; end
		 16'd209: begin FIFO_Data_r[15:0] = {{4{Uqp_PLL_b12	[11]}},Uqp_PLL_b12}; end 
         16'd210: begin FIFO_Data_r[15:0] = {{4{Idp_b12	[11]}},Idp_b12}; end
		 16'd211: begin FIFO_Data_r[15:0] = {{4{Iqp_b12	[11]}},Iqp_b12}; end
		 16'd212: begin FIFO_Data_r[15:0] = {{4{Idn_b12	[11]}},Idn_b12}; end
		 16'd213: begin FIFO_Data_r[15:0] = {{4{Iqn_b12	[11]}},Iqn_b12}; end
		 16'd214: begin FIFO_Data_r[15:0] = {{4{Idp_ref_in_b12	[11]}},Idp_ref_in_b12}; end
		 16'd215: begin FIFO_Data_r[15:0] = {{4{Iqp_ref_in_b12	[11]}},Iqp_ref_in_b12}; end
		 16'd216: begin FIFO_Data_r[15:0] = {{4{Idn_ref_in_b12	[11]}},Idn_ref_in_b12}; end 
		 16'd217: begin FIFO_Data_r[15:0] = {{4{Iqn_ref_in_b12	[11]}},Iqn_ref_in_b12}; end
		 16'd218: begin FIFO_Data_r[15:0] = 0; end  
		 16'd219: begin FIFO_Data_r[15:0] = 0; end
		 16'd220: begin FIFO_Data_r[15:0] = {{4{Mdp_b12	[11]}},Mdp_b12}; end
		 16'd221: begin FIFO_Data_r[15:0] = {{4{Mqp_b12	[11]}},Mqp_b12}; end
		 16'd222: begin FIFO_Data_r[15:0] = {{4{Mdn_b12	[11]}},Mdn_b12}; end
		 16'd223: begin FIFO_Data_r[15:0] = {{4{Mqn_b12	[11]}},Mqn_b12}; end
		 16'd224: begin FIFO_Data_r[15:0] = {{4{Sinwt	[11]}},Sinwt}; end
		 16'd225: begin FIFO_Data_r[15:0] = {{4{Coswt	[11]}},Coswt}; end
		 16'd226: begin FIFO_Data_r[15:0] = {{4{nSinwt	[11]}},nSinwt}; end 
		 16'd227: begin FIFO_Data_r[15:0] = {{4{nCoswt	[11]}},nCoswt}; end
		 16'd228: begin FIFO_Data_r[15:0] = 0; end 
		 16'd229: begin FIFO_Data_r[15:0] = 0; end 
		 16'd230: begin FIFO_Data_r[15:0] = {{4{Ma_b12	[11]}},Ma_b12}; end
		 16'd231: begin FIFO_Data_r[15:0] = {{4{Mb_b12	[11]}},Mb_b12}; end
		 16'd232: begin FIFO_Data_r[15:0] = {{4{Mc_b12	[11]}},Mc_b12}; end
		 16'd233: begin FIFO_Data_r[15:0] = {{4{MaIn_b12	[11]}},MaIn_b12}; end
		 16'd234: begin FIFO_Data_r[15:0] = {{4{MbIn_b12	[11]}},MbIn_b12}; end
		 16'd235: begin FIFO_Data_r[15:0] = {{4{McIn_b12	[11]}},McIn_b12}; end
		 16'd236: begin FIFO_Data_r[15:0] = {{4{MsvA_b12	[11]}},MsvA_b12}; end 
		 16'd237: begin FIFO_Data_r[15:0] = {{4{MsvB_b12	[11]}},MsvB_b12}; end
		 16'd238: begin FIFO_Data_r[15:0] = {{4{MsvC_b12	[11]}},MsvC_b12}; end
		 16'd239: begin FIFO_Data_r[15:0] = 0; end 
		 //====================== debug ==========================
         16'd1000: begin FIFO_Data_r[15:0] = debug0; end 
		 16'd1001: begin FIFO_Data_r[15:0] = debug1; end 
		 16'd1002: begin FIFO_Data_r[15:0] = debug2; end 
		 16'd1003: begin FIFO_Data_r[15:0] = debug3; end 
		 16'd1004: begin FIFO_Data_r[15:0] = debug4; end 
		 16'd1005: begin FIFO_Data_r[15:0] = debug5; end 
		 16'd1006: begin FIFO_Data_r[15:0] = debug6; end 
		 16'd1007: begin FIFO_Data_r[15:0] = debug7; end 
		 16'd1008: begin FIFO_Data_r[15:0] = debug8; end 
		 16'd1009: begin FIFO_Data_r[15:0] = debug9; end  
		 16'd1010: begin FIFO_Data_r[15:0] = debug10; end 
		 16'd1011: begin FIFO_Data_r[15:0] = debug11; end 
		 16'd1012: begin FIFO_Data_r[15:0] = debug12; end 
		 16'd1013: begin FIFO_Data_r[15:0] = debug13; end 
		 16'd1014: begin FIFO_Data_r[15:0] = debug14; end 
		 16'd1015: begin FIFO_Data_r[15:0] = debug15; end 
		 16'd1016: begin FIFO_Data_r[15:0] = debug16; end 
		 16'd1017: begin FIFO_Data_r[15:0] = debug17; end 
		 16'd1018: begin FIFO_Data_r[15:0] = debug18; end 
		 16'd1019: begin FIFO_Data_r[15:0] = debug19; end 
		 16'd1020: begin FIFO_Data_r[15:0] = debug20; end 
		 16'd1021: begin FIFO_Data_r[15:0] = debug21; end 
		 16'd1022: begin FIFO_Data_r[15:0] = debug22; end 
		 16'd1023: begin FIFO_Data_r[15:0] = debug23; end 
		 16'd1024: begin FIFO_Data_r[15:0] = debug24; end 
		 16'd1025: begin FIFO_Data_r[15:0] = debug25; end 
		 16'd1026: begin FIFO_Data_r[15:0] = debug26; end 
		 16'd1027: begin FIFO_Data_r[15:0] = debug27; end 
		 16'd1028: begin FIFO_Data_r[15:0] = debug28; end 
		 16'd1029: begin FIFO_Data_r[15:0] = debug29; end 
		 /* FIFO不受控？？？
			.debug12(dW2_s16), .debug13( wIn_s18[17:2] ),.debug14( dWoutAbs_s16 ), .debug15(InrState),
			.debug16(dwLock_s16),.debug17(dWDead_s16), .debug18(slow_dP_Ffr_b16),.debug19(Qlmt_b16),
			.debug12(wIn_dw_s16), .debug13( w222Flt_dw_s16 ),.debug14( w333Flt_dw_s16 ), .debug15(wFltD3_dw_s16),
			.debug16(FreqDelayCnt),.debug17(FreqHigFlg ? 1000 :0), .debug18(FreqLowFlg ? 1001 :0),.debug19(XvrtDelayFlg ? 1002 :0),*/ 
			
	 endcase
 end 
 assign FIFOX_Data_r = FIFO_Data_r; 
endmodule  // Case1

