// -------------------------------------------------------------
// 
// File Name: Work_RMSP64Ch4_V10\RMSP64Ch4_V10\SimpDualPortRAM_Wrapper_256x24b.v
// Created: 2017-05-12 11:06:47
// 
// Generated by MATLAB 8.6 and HDL Coder 3.7
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpDualPortRAM_Wrapper_256x24b
// Source Path: RMSP64Ch4_V10/RMSP64Ch4_V10/SimpDualPortRAM_Wrapper_256x24b
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimpDualPortRAM_Wrapper_256x24b
          (
           g_clk,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout
          );


  input   g_clk;
  input   signed [23:0] wr_din;  // sfix24
  input   [7:0] wr_addr;  // uint8
  input   wr_en;  // ufix1
  input   [7:0] rd_addr;  // uint8
  output  signed [23:0] rd_dout;  // sfix24




  SimpleDualPortRAM_256x24b   u_SimpleDualPortRAM_256x24b   (.g_clk(g_clk),
                                                             .wr_din(wr_din),  // sfix24
                                                             .wr_addr(wr_addr),  // uint8
                                                             .wr_en(wr_en),  // ufix1
                                                             .rd_addr(rd_addr),  // uint8
                                                             .rd_dout(rd_dout)  // sfix24
                                                             );

endmodule  // SimpDualPortRAM_Wrapper_256x24b

