// -------------------------------------------------------------
// 
// File Name: D:\WORK_NEW2\30KH8\M\Pulse50x1_V1\Pluse50x1_V1\Pulse50x1_V1.v
// Created: 2021-08-30 17:00:10
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Pulse50x1_V1
// Source Path: Pluse50x1_V1/Pulse50x1_V1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Pulse50x1_V1
          (
           g_clk,
           Rst_n,
           wt_b13,
           Pulse50x1_Hz
          );



  input   g_clk;
  input   Rst_n;
  input   [12:0] wt_b13;  // ufix13
  output  Pulse50x1_Hz;

  reg [12:0] Unit_Delay27_out1;  // ufix13
  wire Relational_Operator12_relop1;


  always @(posedge g_clk)
    begin : Unit_Delay27_process
      if (Rst_n == 1'b0) begin
        Unit_Delay27_out1 <= 13'b0000000000000;
      end
      else begin
        Unit_Delay27_out1 <= wt_b13;
      end
    end



  assign Relational_Operator12_relop1 = wt_b13 < Unit_Delay27_out1;



  assign Pulse50x1_Hz = Relational_Operator12_relop1;

endmodule  // Pulse50x1_V1

