// -------------------------------------------------------------
// 
// File Name: Work_NegSeqPhaseAdj_V10\NegSeqPhaseAdj_V10\NegSeqPhaseAdj_V11.v
// Created: 2019-11-08 11:38:04
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: NegSeqPhaseAdj_V11
// Source Path: NegSeqPhaseAdj_V10/NegSeqPhaseAdj_V11
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module NegSeqPhaseAdj_V11
          (
           PhaseAddnSeq_ub13,
           w_co_b12,
           wt_b13,
           Inq_Filtered_b12,
           nwt_b13
          );



  input   [12:0] PhaseAddnSeq_ub13;  // ufix13
  input   signed [11:0] w_co_b12;  // sfix12
  input   [12:0] wt_b13;  // ufix13
  input   signed [11:0] Inq_Filtered_b12;  // sfix12
  output  [12:0] nwt_b13;  // ufix13

  wire signed [15:0] Add4_stage2_1;  // sfix16
  wire signed [15:0] Add4_op_stage2;  // sfix16
  wire signed [11:0] signal1;  // sfix12
  wire signed [15:0] Add4_stage3_1;  // sfix16
  wire signed [15:0] Add4_op_stage3;  // sfix16
  wire signed [11:0] signal2;  // sfix12
  wire signed [23:0] Product_out1;  // sfix24
  wire [12:0] Bit_Slice10_out1;  // ufix13
  wire signed [11:0] Data_Type_Conversion3_out1;  // sfix12
  wire [9:0] Bit_Slice1_out1;  // ufix10
  wire signed [9:0] Data_Type_Conversion1_out1;  // sfix10
  wire signed [15:0] Add4_stage4_sub_temp;  // sfix16
  wire signed [15:0] Add4_stage4_1;  // sfix16
  wire signed [14:0] Add4_out1;  // sfix15
  wire RO7_relop1;
  wire signed [14:0] Add1_out1;  // sfix15
  wire signed [14:0] Switch24_out1;  // sfix15
  wire RO4_relop1;
  wire signed [14:0] Add2_out1;  // sfix15
  wire signed [14:0] Switch21_out1;  // sfix15
  wire [12:0] Data_Type_Conversion2_out1;  // ufix13


  assign Add4_stage2_1 = {3'b0, wt_b13};
  assign Add4_op_stage2 = 16'sb0001111111111111 - Add4_stage2_1;



  assign signal1 = Inq_Filtered_b12;

  assign Add4_stage3_1 = {3'b0, PhaseAddnSeq_ub13};
  assign Add4_op_stage3 = Add4_op_stage2 + Add4_stage3_1;



  assign signal2 = w_co_b12;

  assign Product_out1 = signal1 * signal2;



  assign Bit_Slice10_out1 = Product_out1[23:11];



  assign Data_Type_Conversion3_out1 = $signed(Bit_Slice10_out1[11:0]);



  assign Bit_Slice1_out1 = Data_Type_Conversion3_out1[11:2];



  assign Data_Type_Conversion1_out1 = Bit_Slice1_out1;



  assign Add4_stage4_1 = {{6{Data_Type_Conversion1_out1[9]}}, Data_Type_Conversion1_out1};
  assign Add4_stage4_sub_temp = Add4_op_stage3 + Add4_stage4_1;
  assign Add4_out1 = Add4_stage4_sub_temp[14:0];



  assign RO7_relop1 = Add4_out1 > 15'sb001111111111111;



  assign Add1_out1 = Add4_out1 - 15'sb001111111111111;



  assign Switch24_out1 = (RO7_relop1 == 1'b0 ? Add4_out1 :
              Add1_out1);



  assign RO4_relop1 = Switch24_out1 > 15'sb000000000000000;



  assign Add2_out1 = Switch24_out1 + 15'sb001111111111111;



  assign Switch21_out1 = (RO4_relop1 == 1'b0 ? Add2_out1 :
              Switch24_out1);



  assign Data_Type_Conversion2_out1 = Switch21_out1[12:0];



  assign nwt_b13 = Data_Type_Conversion2_out1;


endmodule  // NegSeqPhaseAdj_V11

