// -------------------------------------------------------------
// 
// File Name: Work_AverFilterP32Ch16_V10\AverFilterP32Ch16_V10\SimpDualPortRAM_Wrapper_512x12b.v
// Created: 2017-04-12 16:08:24
// 
// Generated by MATLAB 8.6 and HDL Coder 3.7
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpDualPortRAM_Wrapper_512x12b
// Source Path: AverFilterP32Ch16_V10/AverFilterP32Ch16_V10/SimpDualPortRAM_Wrapper_512x12b
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AverFilterP32Ch16_V10_SimpDualPortRAM_Wrapper_512x12b
          (
           g_clk,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout
          );


  input   g_clk;
  input   signed [11:0] wr_din;  // sfix12
  input   [8:0] wr_addr;  // ufix9
  input   wr_en;  // ufix1
  input   [8:0] rd_addr;  // ufix9
  output  signed [11:0] rd_dout;  // sfix12




  AverFilterP32Ch16_V10_SimpleDualPortRAM_512x12b   u_AverFilterP32Ch16_V10_SimpleDualPortRAM_512x12b   (.g_clk(g_clk),
                                                             .wr_din(wr_din),  // sfix12
                                                             .wr_addr(wr_addr),  // ufix9
                                                             .wr_en(wr_en),  // ufix1
                                                             .rd_addr(rd_addr),  // ufix9
                                                             .rd_dout(rd_dout)  // sfix12
                                                             );

endmodule  // SimpDualPortRAM_Wrapper_512x12b

