// -------------------------------------------------------------
// 
// File Name: D:\Lmt_V1\Lmt_V1.v
// Created: 2022-05-20 16:41:43
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Lmt_V1
// Source Path: Lmt_V1/Lmt_V1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Lmt_V1
          (
           Lmt_b12,
           In_b12,
           Out_b12
          );



  input   signed [11:0] Lmt_b12;  // sfix12
  input   signed [11:0] In_b12;  // sfix12
  output  signed [11:0] Out_b12;  // sfix12

  wire RO34_relop1;
  wire signed [11:0] Switch297_out1;  // sfix12
  wire signed [12:0] Unary_Minus2_in0;  // sfix13
  wire signed [11:0] Unary_Minus2_out1;  // sfix12
  wire RO33_relop1;
  wire signed [11:0] Switch298_out1;  // sfix12


  assign RO34_relop1 = In_b12 > Lmt_b12;



  assign Switch297_out1 = (RO34_relop1 == 1'b0 ? In_b12 :
              Lmt_b12);



  assign Unary_Minus2_in0 =  - ({Lmt_b12[11], Lmt_b12});
  assign Unary_Minus2_out1 = Unary_Minus2_in0[11:0];



  assign RO33_relop1 = Switch297_out1 < Unary_Minus2_out1;



  assign Switch298_out1 = (RO33_relop1 == 1'b0 ? Switch297_out1 :
              Unary_Minus2_out1);



  assign Out_b12 = Switch298_out1;

endmodule  // Lmt_V1

