// -------------------------------------------------------------
// 
// File Name: D:\FPGA_MZ\AverFilterP128Ch8_V11\AverFilterP128Ch8_V11.v
// Created: 2024-05-13 21:46:28
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: AverFilterP128Ch8_V11
// Source Path: AverFilterP128Ch8_V11/AverFilterP128Ch8_V11
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module AverFilterP128Ch8_V11
          (
           g_clk,
           Rst_n,
           Filter_In0,
           Filter_In1,
           Filter_In2,
           Filter_In3,
           Filter_In4,
           Filter_In5,
           Filter_In6,
           Filter_In7,
           Pulse,
           Filter_Out0,
           Filter_Out1,
           Filter_Out2,
           Filter_Out3,
           Filter_Out4,
           Filter_Out5,
           Filter_Out6,
           Filter_Out7
          );



  input   g_clk;
  input   Rst_n;
  input   signed [11:0] Filter_In0;  // sfix12
  input   signed [11:0] Filter_In1;  // sfix12
  input   signed [11:0] Filter_In2;  // sfix12
  input   signed [11:0] Filter_In3;  // sfix12
  input   signed [11:0] Filter_In4;  // sfix12
  input   signed [11:0] Filter_In5;  // sfix12
  input   signed [11:0] Filter_In6;  // sfix12
  input   signed [11:0] Filter_In7;  // sfix12
  input   Pulse;
  output  signed [11:0] Filter_Out0;  // sfix12
  output  signed [11:0] Filter_Out1;  // sfix12
  output  signed [11:0] Filter_Out2;  // sfix12
  output  signed [11:0] Filter_Out3;  // sfix12
  output  signed [11:0] Filter_Out4;  // sfix12
  output  signed [11:0] Filter_Out5;  // sfix12
  output  signed [11:0] Filter_Out6;  // sfix12
  output  signed [11:0] Filter_Out7;  // sfix12

  reg [2:0] Unit_Delay7_out1;  // ufix3
  wire [2:0] Add1_out1;  // ufix3
  wire CT51_out1;
  wire CT12_out1;
  reg  Unit_Delay54_out1;
  wire Switch20_out1;
  wire Switch17_out1;
  wire Or3_out1;
  wire Switch208_out1;
  reg  Unit_Delay55_out1;
  wire CT70_out1;
  wire Or2_out1;
  wire [9:0] Switch83_out1;  // ufix10
  reg [9:0] Unit_Delay32_out1;  // ufix10
  wire [9:0] Add11_out1;  // ufix10
  wire Ro10_relop1;
  reg  Unit_Delay57_out1;
  wire Switch49_out1;
  wire Switch105_out1;
  reg  Unit_Delay1_out1;
  wire CT55_out1;
  wire CT57_out1;
  wire CT59_out1;
  wire CT61_out1;
  wire CT2_out1;
  wire CT4_out1;
  wire CT6_out1;
  wire CT8_out1;
  wire signed [11:0] signal1;  // sfix12
  wire signed [11:0] s;  // sfix12
  wire signed [11:0] signal1_1;  // sfix12
  wire signed [11:0] s_1;  // sfix12
  wire signed [11:0] signal1_2;  // sfix12
  wire signed [11:0] s_2;  // sfix12
  wire signed [11:0] signal1_3;  // sfix12
  wire signed [11:0] s_3;  // sfix12
  wire signed [11:0] signal1_4;  // sfix12
  wire signed [11:0] s_4;  // sfix12
  wire signed [11:0] signal1_5;  // sfix12
  wire signed [11:0] s_5;  // sfix12
  wire signed [11:0] signal1_6;  // sfix12
  wire signed [11:0] s_6;  // sfix12
  wire switch_compare_1;
  wire signed [11:0] signal1_7;  // sfix12
  wire signed [11:0] signal1_8;  // sfix12
  wire signed [11:0] signal1_9;  // sfix12
  wire signed [11:0] Switch84_out1;  // sfix12
  wire signed [11:0] Switch97_out1;  // sfix12
  wire [9:0] Add12_out1;  // ufix10
  wire signed [11:0] Simple_Dual_Port_RAM2_out1;  // sfix12
  wire switch_compare_1_1;
  wire signed [11:0] Switch98_out1;  // sfix12
  wire signed [19:0] Add7_stage2_1;  // sfix20
  wire signed [19:0] Add7_stage2_2;  // sfix20
  wire signed [19:0] Add7_op_stage2;  // sfix20
  wire CT7_out1;
  wire CT5_out1;
  wire CT3_out1;
  wire CT1_out1;
  wire CT60_out1;
  wire CT58_out1;
  wire CT56_out1;
  reg signed [18:0] Unit_Delay30_out1;  // sfix19
  wire signed [18:0] B23_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay33_out1;  // sfix19
  wire signed [18:0] Switch79_out1;  // sfix19
  wire signed [18:0] Switch87_out1;  // sfix19
  wire signed [18:0] B24_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay34_out1;  // sfix19
  wire signed [18:0] Switch89_out1;  // sfix19
  wire signed [18:0] B25_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay35_out1;  // sfix19
  wire signed [18:0] Switch91_out1;  // sfix19
  wire signed [18:0] B26_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay2_out1;  // sfix19
  wire signed [18:0] Switch1_out1;  // sfix19
  wire signed [18:0] B1_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay3_out1;  // sfix19
  wire signed [18:0] Switch3_out1;  // sfix19
  wire signed [18:0] B2_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay4_out1;  // sfix19
  wire signed [18:0] Switch5_out1;  // sfix19
  wire signed [18:0] B3_out1_signal2;  // sfix19
  reg signed [18:0] Unit_Delay5_out1;  // sfix19
  wire signed [18:0] B4_out1_signal2;  // sfix19
  wire signed [18:0] Switch7_out1;  // sfix19
  wire signed [18:0] B4_out1_signal2_1;  // sfix19
  wire signed [18:0] signal2;  // sfix19
  wire signed [18:0] s_7;  // sfix19
  wire signed [18:0] signal2_1;  // sfix19
  wire signed [18:0] s_8;  // sfix19
  wire signed [18:0] signal2_2;  // sfix19
  wire signed [18:0] s_9;  // sfix19
  wire signed [18:0] signal2_3;  // sfix19
  wire signed [18:0] s_10;  // sfix19
  wire signed [18:0] signal2_4;  // sfix19
  wire signed [18:0] s_11;  // sfix19
  wire signed [18:0] signal2_5;  // sfix19
  wire signed [18:0] s_12;  // sfix19
  wire signed [18:0] signal2_6;  // sfix19
  wire signed [18:0] s_13;  // sfix19
  wire signed [18:0] signal2_7;  // sfix19
  wire signed [18:0] signal2_8;  // sfix19
  wire signed [18:0] signal2_9;  // sfix19
  wire signed [19:0] Add7_stage3_add_temp;  // sfix20
  wire signed [19:0] Add7_stage3_1;  // sfix20
  wire signed [18:0] Add7_out1;  // sfix19
  wire signed [18:0] Switch80_out1;  // sfix19
  wire [11:0] Bit_Slice6_out1;  // ufix12
  wire signed [11:0] Data_Type_S11_out1;  // sfix12
  wire [11:0] Bit_Slice1_out1;  // ufix12
  wire signed [11:0] Data_Type_S12_out1;  // sfix12
  wire [11:0] Bit_Slice2_out1;  // ufix12
  wire signed [11:0] Data_Type_S13_out1;  // sfix12
  wire [11:0] Bit_Slice3_out1;  // ufix12
  wire signed [11:0] Data_Type_S15_out1;  // sfix12
  wire [11:0] Bit_Slice4_out1;  // ufix12
  wire signed [11:0] Data_Type_S1_out1;  // sfix12
  wire [11:0] Bit_Slice5_out1;  // ufix12
  wire signed [11:0] Data_Type_S2_out1;  // sfix12
  wire [11:0] Bit_Slice7_out1;  // ufix12
  wire signed [11:0] Data_Type_S3_out1;  // sfix12
  wire [11:0] Bit_Slice8_out1;  // ufix12
  wire signed [11:0] Data_Type_S4_out1;  // sfix12


  assign Add1_out1 = 3'b001 + Unit_Delay7_out1;



  always @(posedge g_clk)
    begin : Unit_Delay7_process
      if (Rst_n == 1'b0) begin
        Unit_Delay7_out1 <= 3'b000;
      end
      else begin
        Unit_Delay7_out1 <= Add1_out1;
      end
    end



  assign CT51_out1 = Unit_Delay7_out1 == 3'b000;



  assign CT12_out1 = Unit_Delay7_out1 == 3'b000;



  assign Switch20_out1 = (Pulse == 1'b0 ? Unit_Delay54_out1 :
              1'b1);



  assign Switch17_out1 = (CT12_out1 == 1'b0 ? Switch20_out1 :
              1'b0);



  always @(posedge g_clk)
    begin : Unit_Delay54_process
      if (Rst_n == 1'b0) begin
        Unit_Delay54_out1 <= 1'b0;
      end
      else begin
        Unit_Delay54_out1 <= Switch17_out1;
      end
    end



  assign Or3_out1 = Pulse | Unit_Delay54_out1;



  always @(posedge g_clk)
    begin : Unit_Delay55_process
      if (Rst_n == 1'b0) begin
        Unit_Delay55_out1 <= 1'b0;
      end
      else begin
        Unit_Delay55_out1 <= Switch208_out1;
      end
    end



  assign Switch208_out1 = (CT12_out1 == 1'b0 ? Unit_Delay55_out1 :
              Or3_out1);



  assign CT70_out1 = Unit_Delay7_out1 == 3'b000;



  assign Or2_out1 = Switch208_out1 & CT70_out1;



  assign Switch83_out1 = (Switch208_out1 == 1'b0 ? 10'b0000000000 :
              10'b0000000001);



  assign Add11_out1 = Switch83_out1 + Unit_Delay32_out1;



  always @(posedge g_clk)
    begin : Unit_Delay32_process
      if (Rst_n == 1'b0) begin
        Unit_Delay32_out1 <= 10'b0000000000;
      end
      else begin
        Unit_Delay32_out1 <= Add11_out1;
      end
    end



  assign Ro10_relop1 = Unit_Delay32_out1 > Add11_out1;



  assign Switch49_out1 = (Ro10_relop1 == 1'b0 ? Unit_Delay57_out1 :
              1'b1);



  always @(posedge g_clk)
    begin : Unit_Delay57_process
      if (Rst_n == 1'b0) begin
        Unit_Delay57_out1 <= 1'b0;
      end
      else begin
        Unit_Delay57_out1 <= Switch49_out1;
      end
    end



  always @(posedge g_clk)
    begin : Unit_Delay1_process
      if (Rst_n == 1'b0) begin
        Unit_Delay1_out1 <= 1'b0;
      end
      else begin
        Unit_Delay1_out1 <= Switch105_out1;
      end
    end



  assign Switch105_out1 = (Or2_out1 == 1'b0 ? Unit_Delay1_out1 :
              Unit_Delay57_out1);



  assign CT55_out1 = Unit_Delay7_out1 == 3'b000;



  assign CT57_out1 = Unit_Delay7_out1 == 3'b001;



  assign CT59_out1 = Unit_Delay7_out1 == 3'b010;



  assign CT61_out1 = Unit_Delay7_out1 == 3'b011;



  assign CT2_out1 = Unit_Delay7_out1 == 3'b100;



  assign CT4_out1 = Unit_Delay7_out1 == 3'b101;



  assign CT6_out1 = Unit_Delay7_out1 == 3'b110;



  assign CT8_out1 = Unit_Delay7_out1 == 3'b111;



  assign signal1 = (CT8_out1 == 1'b0 ? Filter_In7 :
              Filter_In7);



  assign s = signal1;

  assign signal1_1 = (CT6_out1 == 1'b0 ? s :
              Filter_In6);



  assign s_1 = signal1_1;

  assign signal1_2 = (CT4_out1 == 1'b0 ? s_1 :
              Filter_In5);



  assign s_2 = signal1_2;

  assign signal1_3 = (CT2_out1 == 1'b0 ? s_2 :
              Filter_In4);



  assign s_3 = signal1_3;

  assign signal1_4 = (CT61_out1 == 1'b0 ? s_3 :
              Filter_In3);



  assign s_4 = signal1_4;

  assign signal1_5 = (CT59_out1 == 1'b0 ? s_4 :
              Filter_In2);



  assign s_5 = signal1_5;

  assign signal1_6 = (CT57_out1 == 1'b0 ? s_5 :
              Filter_In1);



  assign s_6 = signal1_6;

  assign switch_compare_1 = Switch105_out1 > 1'b0;



  assign signal1_7 = (CT55_out1 == 1'b0 ? s_6 :
              Filter_In0);



  assign signal1_8 = signal1_7;

  assign signal1_9 = signal1_8;

  assign Switch84_out1 = (switch_compare_1 == 1'b0 ? 12'sb000000000000 :
              signal1_9);



  assign Switch97_out1 = (Switch208_out1 == 1'b0 ? 12'sb000000000000 :
              Switch84_out1);



  assign Add12_out1 = Add11_out1 + 10'b0000000001;



  SimpDualPortRAM_Wrapper_generic   #  (.AddrWidth(10),
                                        .DataWidth(12)
                                        )
                                    u_Simple_Dual_Port_RAM2   (.g_clk(g_clk),
                                                               .wr_din(Switch84_out1),
                                                               .wr_addr(Add11_out1),
                                                               .wr_en(Switch208_out1),
                                                               .rd_addr(Add12_out1),
                                                               .rd_dout(Simple_Dual_Port_RAM2_out1)
                                                               );

  assign switch_compare_1_1 = Switch105_out1 > 1'b0;



  assign Switch98_out1 = (Switch208_out1 == 1'b0 ? 12'sb000000000000 :
              Simple_Dual_Port_RAM2_out1);



  assign Add7_stage2_1 = {{8{Switch97_out1[11]}}, Switch97_out1};
  assign Add7_stage2_2 = {{8{Switch98_out1[11]}}, Switch98_out1};
  assign Add7_op_stage2 = Add7_stage2_1 - Add7_stage2_2;



  assign CT7_out1 = Unit_Delay7_out1 == 3'b111;



  assign CT5_out1 = Unit_Delay7_out1 == 3'b110;



  assign CT3_out1 = Unit_Delay7_out1 == 3'b101;



  assign CT1_out1 = Unit_Delay7_out1 == 3'b100;



  assign CT60_out1 = Unit_Delay7_out1 == 3'b011;



  assign CT58_out1 = Unit_Delay7_out1 == 3'b010;



  assign CT56_out1 = Unit_Delay7_out1 == 3'b001;



  assign B23_out1_signal2 = Unit_Delay30_out1;

  assign Switch87_out1 = (CT56_out1 == 1'b0 ? Unit_Delay33_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay33_process
      if (Rst_n == 1'b0) begin
        Unit_Delay33_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay33_out1 <= Switch87_out1;
      end
    end



  assign B24_out1_signal2 = Unit_Delay33_out1;

  assign Switch89_out1 = (CT58_out1 == 1'b0 ? Unit_Delay34_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay34_process
      if (Rst_n == 1'b0) begin
        Unit_Delay34_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay34_out1 <= Switch89_out1;
      end
    end



  assign B25_out1_signal2 = Unit_Delay34_out1;

  assign Switch91_out1 = (CT60_out1 == 1'b0 ? Unit_Delay35_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay35_process
      if (Rst_n == 1'b0) begin
        Unit_Delay35_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay35_out1 <= Switch91_out1;
      end
    end



  assign B26_out1_signal2 = Unit_Delay35_out1;

  assign Switch1_out1 = (CT1_out1 == 1'b0 ? Unit_Delay2_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay2_process
      if (Rst_n == 1'b0) begin
        Unit_Delay2_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay2_out1 <= Switch1_out1;
      end
    end



  assign B1_out1_signal2 = Unit_Delay2_out1;

  assign Switch3_out1 = (CT3_out1 == 1'b0 ? Unit_Delay3_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay3_process
      if (Rst_n == 1'b0) begin
        Unit_Delay3_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay3_out1 <= Switch3_out1;
      end
    end



  assign B2_out1_signal2 = Unit_Delay3_out1;

  assign Switch5_out1 = (CT5_out1 == 1'b0 ? Unit_Delay4_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay4_process
      if (Rst_n == 1'b0) begin
        Unit_Delay4_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay4_out1 <= Switch5_out1;
      end
    end



  assign B3_out1_signal2 = Unit_Delay4_out1;

  assign B4_out1_signal2 = Unit_Delay5_out1;

  assign Switch7_out1 = (CT7_out1 == 1'b0 ? Unit_Delay5_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay5_process
      if (Rst_n == 1'b0) begin
        Unit_Delay5_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay5_out1 <= Switch7_out1;
      end
    end



  assign B4_out1_signal2_1 = Unit_Delay5_out1;

  assign signal2 = (CT8_out1 == 1'b0 ? B4_out1_signal2_1 :
              B4_out1_signal2);



  assign s_7 = signal2;

  assign signal2_1 = (CT6_out1 == 1'b0 ? s_7 :
              B3_out1_signal2);



  assign s_8 = signal2_1;

  assign signal2_2 = (CT4_out1 == 1'b0 ? s_8 :
              B2_out1_signal2);



  assign s_9 = signal2_2;

  assign signal2_3 = (CT2_out1 == 1'b0 ? s_9 :
              B1_out1_signal2);



  assign s_10 = signal2_3;

  assign signal2_4 = (CT61_out1 == 1'b0 ? s_10 :
              B26_out1_signal2);



  assign s_11 = signal2_4;

  assign signal2_5 = (CT59_out1 == 1'b0 ? s_11 :
              B25_out1_signal2);



  assign s_12 = signal2_5;

  assign signal2_6 = (CT57_out1 == 1'b0 ? s_12 :
              B24_out1_signal2);



  assign s_13 = signal2_6;

  assign signal2_7 = (CT55_out1 == 1'b0 ? s_13 :
              B23_out1_signal2);



  assign signal2_8 = signal2_7;

  assign signal2_9 = signal2_8;

  assign Add7_stage3_1 = {signal2_9[18], signal2_9};
  assign Add7_stage3_add_temp = Add7_op_stage2 + Add7_stage3_1;
  assign Add7_out1 = Add7_stage3_add_temp[18:0];



  assign Switch79_out1 = (switch_compare_1_1 == 1'b0 ? 19'sb0000000000000000000 :
              Add7_out1);



  assign Switch80_out1 = (CT51_out1 == 1'b0 ? Unit_Delay30_out1 :
              Switch79_out1);



  always @(posedge g_clk)
    begin : Unit_Delay30_process
      if (Rst_n == 1'b0) begin
        Unit_Delay30_out1 <= 19'sb0000000000000000000;
      end
      else begin
        Unit_Delay30_out1 <= Switch80_out1;
      end
    end



  assign Bit_Slice6_out1 = Unit_Delay30_out1[18:7];



  assign Data_Type_S11_out1 = Bit_Slice6_out1;



  assign Filter_Out0 = Data_Type_S11_out1;

  assign Bit_Slice1_out1 = Unit_Delay33_out1[18:7];



  assign Data_Type_S12_out1 = Bit_Slice1_out1;



  assign Filter_Out1 = Data_Type_S12_out1;

  assign Bit_Slice2_out1 = Unit_Delay34_out1[18:7];



  assign Data_Type_S13_out1 = Bit_Slice2_out1;



  assign Filter_Out2 = Data_Type_S13_out1;

  assign Bit_Slice3_out1 = Unit_Delay35_out1[18:7];



  assign Data_Type_S15_out1 = Bit_Slice3_out1;



  assign Filter_Out3 = Data_Type_S15_out1;

  assign Bit_Slice4_out1 = Unit_Delay2_out1[18:7];



  assign Data_Type_S1_out1 = Bit_Slice4_out1;



  assign Filter_Out4 = Data_Type_S1_out1;

  assign Bit_Slice5_out1 = Unit_Delay3_out1[18:7];



  assign Data_Type_S2_out1 = Bit_Slice5_out1;



  assign Filter_Out5 = Data_Type_S2_out1;

  assign Bit_Slice7_out1 = Unit_Delay4_out1[18:7];



  assign Data_Type_S3_out1 = Bit_Slice7_out1;



  assign Filter_Out6 = Data_Type_S3_out1;

  assign Bit_Slice8_out1 = Unit_Delay5_out1[18:7];



  assign Data_Type_S4_out1 = Bit_Slice8_out1;



  assign Filter_Out7 = Data_Type_S4_out1;

endmodule  // AverFilterP128Ch8_V11

