// -------------------------------------------------------------
// 
// File Name: D:\FPGA_MZ\LoadMabc_VZ1\LoadMabc_VZ1.v
// Created: 2024-07-23 19:27:34
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LoadMabc_VZ1
// Source Path: LoadMabc_VZ1/LoadMabc_VZ1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LoadMabc_VZ1
          (
           g_clk,
           Rst_n,
           Carryb12,
           MaIn_s12,
           MbIn_s12,
           McIn_s12,
           MaOut_s12,
           MbOut_s12,
           McOut_s12,
           PwmLoadPluse
          );



  input   g_clk;
  input   Rst_n;
  input   signed [11:0] Carryb12;  // sfix12
  input   signed [11:0] MaIn_s12;  // sfix12
  input   signed [11:0] MbIn_s12;  // sfix12
  input   signed [11:0] McIn_s12;  // sfix12
  output  signed [11:0] MaOut_s12;  // sfix12
  output  signed [11:0] MbOut_s12;  // sfix12
  output  signed [11:0] McOut_s12;  // sfix12
  output  PwmLoadPluse;

  wire [10:0] Bit_Slice9_out1;  // ufix11
  reg [10:0] Unit_Delay55_out1;  // ufix11
  wire Relational_Operator2_relop1;
  wire signed [11:0] Switch107_out1;  // sfix12
  reg signed [11:0] Unit_Delay39_out1;  // sfix12
  wire RO6_relop1;
  wire signed [11:0] Switch41_out1;  // sfix12
  wire signed [11:0] Unary_Minus1_out1;  // sfix12
  wire RO1_relop1;
  wire signed [11:0] Switch1_out1;  // sfix12
  wire signed [11:0] Switch107_out1_1;  // sfix12
  reg signed [11:0] Unit_Delay39_out1_1;  // sfix12
  wire RO61_relop1;
  wire signed [11:0] Switch41_out1_1;  // sfix12
  wire signed [11:0] Unary_Minus1_out1_1;  // sfix12
  wire RO11_relop1;
  wire signed [11:0] Switch1_out1_1;  // sfix12
  wire signed [11:0] Switch107_out1_2;  // sfix12
  reg signed [11:0] Unit_Delay39_out1_2;  // sfix12
  wire RO62_relop1;
  wire signed [11:0] Switch41_out1_2;  // sfix12
  wire signed [11:0] Unary_Minus1_out1_2;  // sfix12
  wire RO12_relop1;
  wire signed [11:0] Switch1_out1_2;  // sfix12


  assign Bit_Slice9_out1 = Carryb12[10:0];



  always @(posedge g_clk)
    begin : Unit_Delay55_process
      if (Rst_n == 1'b0) begin
        Unit_Delay55_out1 <= 11'b00000000000;
      end
      else begin
        Unit_Delay55_out1 <= Bit_Slice9_out1;
      end
    end



  assign Relational_Operator2_relop1 = Bit_Slice9_out1 < Unit_Delay55_out1;



  always @(posedge g_clk)
    begin : Unit_Delay391_process
      if (Rst_n == 1'b0) begin
        Unit_Delay39_out1 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay39_out1 <= Switch107_out1;
      end
    end



  assign Switch107_out1 = (Relational_Operator2_relop1 == 1'b0 ? Unit_Delay39_out1 :
              MaIn_s12);



  assign RO6_relop1 = Switch107_out1 > 12'sb011111010000;



  assign Switch41_out1 = (RO6_relop1 == 1'b0 ? Switch107_out1 :
              12'sb011111010000);



  assign Unary_Minus1_out1 = 12'sb100000110000;



  assign RO1_relop1 = Switch41_out1 < Unary_Minus1_out1;



  assign Switch1_out1 = (RO1_relop1 == 1'b0 ? Switch41_out1 :
              Unary_Minus1_out1);



  assign MaOut_s12 = Switch1_out1;

  always @(posedge g_clk)
    begin : Unit_Delay39_process
      if (Rst_n == 1'b0) begin
        Unit_Delay39_out1_1 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay39_out1_1 <= Switch107_out1_1;
      end
    end



  assign Switch107_out1_1 = (Relational_Operator2_relop1 == 1'b0 ? Unit_Delay39_out1_1 :
              MbIn_s12);



  assign RO61_relop1 = Switch107_out1_1 > 12'sb011111010000;



  assign Switch41_out1_1 = (RO61_relop1 == 1'b0 ? Switch107_out1_1 :
              12'sb011111010000);



  assign Unary_Minus1_out1_1 = 12'sb100000110000;



  assign RO11_relop1 = Switch41_out1_1 < Unary_Minus1_out1_1;



  assign Switch1_out1_1 = (RO11_relop1 == 1'b0 ? Switch41_out1_1 :
              Unary_Minus1_out1_1);



  assign MbOut_s12 = Switch1_out1_1;

  always @(posedge g_clk)
    begin : Unit_Delay392_process
      if (Rst_n == 1'b0) begin
        Unit_Delay39_out1_2 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay39_out1_2 <= Switch107_out1_2;
      end
    end



  assign Switch107_out1_2 = (Relational_Operator2_relop1 == 1'b0 ? Unit_Delay39_out1_2 :
              McIn_s12);



  assign RO62_relop1 = Switch107_out1_2 > 12'sb011111010000;



  assign Switch41_out1_2 = (RO62_relop1 == 1'b0 ? Switch107_out1_2 :
              12'sb011111010000);



  assign Unary_Minus1_out1_2 = 12'sb100000110000;



  assign RO12_relop1 = Switch41_out1_2 < Unary_Minus1_out1_2;



  assign Switch1_out1_2 = (RO12_relop1 == 1'b0 ? Switch41_out1_2 :
              Unary_Minus1_out1_2);



  assign McOut_s12 = Switch1_out1_2;

  assign PwmLoadPluse = Relational_Operator2_relop1;

endmodule  // LoadMabc_VZ1

