// -------------------------------------------------------------
// 
// File Name: D:\Temp2DrvLogic_V12_3L\Temp2DrvLogic_V12_3L.v
// Created: 2022-12-23 15:10:32
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 4e-08
// Target subsystem base rate: 4e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Temp2DrvLogic_V12_3L
// Source Path: Temp2DrvLogic_V12_3L/Temp2DrvLogic_V12_3L
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Temp2DrvLogic_V12_3L
          (
           g_clk,
           Rst_n,
           Pulse_4096Hz,
           IGBTa_Temp,
           IGBTb_Temp,
           IGBTc_Temp,
           IGBTTmepFanOn_Thr,
           IGBTTmepFanOff_Thr,
           IGBTTmepHotOn_Thr,
           IGBTTmepHotOff_Thr,
           IGBT_OT_Thr,
           FanOn_Drv,
           HotOn_Drv,
           IGBTOT_Err
          );



  input   g_clk;
  input   Rst_n;
  input   Pulse_4096Hz;
  input   [11:0] IGBTa_Temp;  // ufix12
  input   [11:0] IGBTb_Temp;  // ufix12
  input   [11:0] IGBTc_Temp;  // ufix12
  input   [11:0] IGBTTmepFanOn_Thr;  // ufix12
  input   [11:0] IGBTTmepFanOff_Thr;  // ufix12
  input   [11:0] IGBTTmepHotOn_Thr;  // ufix12
  input   [11:0] IGBTTmepHotOff_Thr;  // ufix12
  input   [11:0] IGBT_OT_Thr;  // ufix12
  output  signed [11:0] FanOn_Drv;  // sfix12
  output  signed [11:0] HotOn_Drv;  // sfix12
  output  IGBTOT_Err;

  wire RO_relop1;
  wire switch_compare_1;
  wire [11:0] Switch14_out1;  // ufix12
  wire RO1_relop1;
  wire switch_compare_1_1;
  wire [11:0] Switch2_out1;  // ufix12
  wire Relational_Operator2_relop1;
  wire Relational_Operator3_relop1;
  wire switch_compare_1_2;
  wire signed [11:0] Constant19_out1_dtc;  // sfix12
  wire signed [11:0] Constant18_out1_dtc;  // sfix12
  reg signed [11:0] Unit_Delay6_out1;  // sfix12
  wire signed [11:0] Switch18_out1;  // sfix12
  wire signed [11:0] Switch17_out1;  // sfix12
  wire RO2_relop1;
  wire switch_compare_1_3;
  wire [11:0] Switch1_out1;  // ufix12
  wire RO3_relop1;
  wire switch_compare_1_4;
  wire [11:0] Switch8_out1;  // ufix12
  wire Relational_Operator1_relop1;
  wire Relational_Operator4_relop1;
  wire switch_compare_1_5;
  wire signed [11:0] Constant2_out1_dtc;  // sfix12
  wire signed [11:0] Constant1_out1_dtc;  // sfix12
  reg signed [11:0] Unit_Delay1_out1;  // sfix12
  wire signed [11:0] Switch4_out1;  // sfix12
  wire signed [11:0] Switch3_out1;  // sfix12
  wire Relational_Operator5_relop1;
  wire signed [7:0] Switch58_out1;  // int8
  wire signed [7:0] Switch6_out1;  // int8
  wire CT10_out1;
  wire signed [15:0] Add3_out1;  // int16
  wire signed [15:0] Switch28_out1;  // int16
  wire Dy2_relop1;
  wire signed [15:0] Switch27_out1;  // int16
  reg signed [15:0] Unit_Delay2_out1;  // int16
  wire signed [16:0] Add3_add_temp;  // sfix17
  wire signed [16:0] Add3_1;  // sfix17
  wire signed [16:0] Add3_2;  // sfix17
  wire Data_Type_Conversion_out1;
  reg  Unit_Delay3_out1;
  wire Switch29_out1;
  wire Switch30_out1;


  assign RO_relop1 = IGBTa_Temp > IGBTb_Temp;



  assign switch_compare_1 = RO_relop1 > 1'b0;



  assign Switch14_out1 = (switch_compare_1 == 1'b0 ? IGBTb_Temp :
              IGBTa_Temp);



  assign RO1_relop1 = Switch14_out1 > IGBTc_Temp;



  assign switch_compare_1_1 = RO1_relop1 > 1'b0;



  assign Switch2_out1 = (switch_compare_1_1 == 1'b0 ? IGBTc_Temp :
              Switch14_out1);



  assign Relational_Operator2_relop1 = Switch2_out1 > IGBTTmepFanOn_Thr;



  assign Relational_Operator3_relop1 = Switch2_out1 < IGBTTmepFanOff_Thr;



  assign switch_compare_1_2 = Relational_Operator3_relop1 > 1'b0;



  assign Constant19_out1_dtc = 12'sb000000000000;



  assign Constant18_out1_dtc = 12'sb000000000001;



  assign Switch18_out1 = (switch_compare_1_2 == 1'b0 ? Unit_Delay6_out1 :
              Constant19_out1_dtc);



  assign Switch17_out1 = (Relational_Operator2_relop1 == 1'b0 ? Switch18_out1 :
              Constant18_out1_dtc);



  always @(posedge g_clk)
    begin : Unit_Delay6_process
      if (Rst_n == 1'b0) begin
        Unit_Delay6_out1 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay6_out1 <= Switch17_out1;
      end
    end



  assign FanOn_Drv = Unit_Delay6_out1;

  assign RO2_relop1 = IGBTa_Temp < IGBTb_Temp;



  assign switch_compare_1_3 = RO2_relop1 > 1'b0;



  assign Switch1_out1 = (switch_compare_1_3 == 1'b0 ? IGBTb_Temp :
              IGBTa_Temp);



  assign RO3_relop1 = Switch1_out1 < IGBTc_Temp;



  assign switch_compare_1_4 = RO3_relop1 > 1'b0;



  assign Switch8_out1 = (switch_compare_1_4 == 1'b0 ? IGBTc_Temp :
              Switch1_out1);



  assign Relational_Operator1_relop1 = Switch8_out1 < IGBTTmepHotOn_Thr;



  assign Relational_Operator4_relop1 = Switch8_out1 > IGBTTmepHotOff_Thr;



  assign switch_compare_1_5 = Relational_Operator4_relop1 > 1'b0;



  assign Constant2_out1_dtc = 12'sb000000000000;



  assign Constant1_out1_dtc = 12'sb000000000001;



  assign Switch4_out1 = (switch_compare_1_5 == 1'b0 ? Unit_Delay1_out1 :
              Constant2_out1_dtc);



  assign Switch3_out1 = (Relational_Operator1_relop1 == 1'b0 ? Switch4_out1 :
              Constant1_out1_dtc);



  always @(posedge g_clk)
    begin : Unit_Delay1_process
      if (Rst_n == 1'b0) begin
        Unit_Delay1_out1 <= 12'sb000000000000;
      end
      else begin
        Unit_Delay1_out1 <= Switch3_out1;
      end
    end



  assign HotOn_Drv = Unit_Delay1_out1;

  assign Relational_Operator5_relop1 = Switch2_out1 > IGBT_OT_Thr;



  assign Switch58_out1 = (Relational_Operator5_relop1 == 1'b0 ? 8'sb11111111 :
              8'sb00000001);



  assign Switch6_out1 = (Pulse_4096Hz == 1'b0 ? 8'sb00000000 :
              Switch58_out1);



  assign Switch28_out1 = (CT10_out1 == 1'b0 ? Add3_out1 :
              16'sb0000000000000000);



  assign Dy2_relop1 = Switch28_out1 >= 16'sb0011000000000000;



  assign Switch27_out1 = (Dy2_relop1 == 1'b0 ? Switch28_out1 :
              16'sb0011000000000000);



  always @(posedge g_clk)
    begin : Unit_Delay2_process
      if (Rst_n == 1'b0) begin
        Unit_Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        Unit_Delay2_out1 <= Switch27_out1;
      end
    end



  assign Add3_1 = {{9{Switch6_out1[7]}}, Switch6_out1};
  assign Add3_2 = {Unit_Delay2_out1[15], Unit_Delay2_out1};
  assign Add3_add_temp = Add3_1 + Add3_2;
  assign Add3_out1 = Add3_add_temp[15:0];



  assign CT10_out1 = Add3_out1 <= 16'sb0000000000000000;



  always @(posedge g_clk)
    begin : Unit_Delay3_process
      if (Rst_n == 1'b0) begin
        Unit_Delay3_out1 <= 1'b0;
      end
      else begin
        Unit_Delay3_out1 <= Data_Type_Conversion_out1;
      end
    end



  assign Switch29_out1 = (Dy2_relop1 == 1'b0 ? Unit_Delay3_out1 :
              1'b1);



  assign Switch30_out1 = (CT10_out1 == 1'b0 ? Switch29_out1 :
              1'b0);



  assign Data_Type_Conversion_out1 = (Switch30_out1 != 1'b0 ? 1'b1 :
              1'b0);



  assign IGBTOT_Err = Data_Type_Conversion_out1;

endmodule  // Temp2DrvLogic_V12_3L

