# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/io.xdc

# IP: ip/sintab/sintab.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sintab || ORIG_REF_NAME==sintab} -quiet] -quiet

# IP: ip/mmcm0/mmcm0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mmcm0 || ORIG_REF_NAME==mmcm0} -quiet] -quiet

# XDC: ip/sintab/sintab_ooc.xdc

# XDC: ip/mmcm0/mmcm0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm0 || ORIG_REF_NAME==mmcm0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/mmcm0/mmcm0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm0 || ORIG_REF_NAME==mmcm0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/mmcm0/mmcm0_ooc.xdc
