# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s75fgga484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.cache/wt [current_project]
set_property parent.project_path D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/coe/dst4.coe
read_verilog -library xil_defaultlib -sv {
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/arm3358_pkg.sv
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/NEPCS_100_V01_Top.sv
}
read_verilog -library xil_defaultlib {
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/ABC2DQ_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/AD7607Drv_VZ10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/APWMTimeK24_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/NewARM_comm202410/ARM_commZJ.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/Abs_b12_V3.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AdSubZero_V1/AdSubZero_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/AddSub_b16_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/AnalogMonitorWarn_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AnalogMonitor_V10/AnalogMonitor_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/AnpcPwmErrChk.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/AverFilter8192P_b18_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/AverFilterP128Ch4_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP128Ch4_V11/AverFilterP128Ch4_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/AverFilterP128Ch8_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP32Ch16_V10/AverFilterP32Ch16_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP32Ch8_V10/AverFilterP32Ch8_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_BitFilterCh2_V11a/BitFilterCh2_V11a.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_BitFilter_V11/BitFilter_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/BitFilter_VC1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/CBC_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_CabinetHeatOV_V10/CabinetHeatOV_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Drv/ClkPulse_Gen.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/NewARM_comm202410/DPRAMZ.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/NewARM_comm202410/DPRAM_LONG_Z.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/FaultRey_VZ2.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_Fiber/FiberToCarrySync_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/NewARM_comm202410/FifoSelZ.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/FreqActivePower/FreqActivePower_VZ5.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_FrequencyMonitor_V10/FrequencyMonitor_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_GridPll_V20/GridPll_V20.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/IGBTErrChk.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/IacLmt_VZ1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InsVoltCurrMonitor_V20/InsVoltCurrMonitor_V21.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InvControlLoop3L_V40a/InvControlLoop3L_V40b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_IsLandDetectLogic_V30/IsLandDetectLogic_V30.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_IsLandDetect_V10/IsLandDetect_V10_block.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/L3_UnB_Z13.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InvControlLoop3L_V40a/LmtB16_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InvControlLoop3L_V40a/LoadMabc_VZ3.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InvControlLoop3L_V40a/Msel_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_MulMpy_V10/MulMpy_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/NEPCS_100_V01_FSM.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/NEPCS_100_V01_PLD_xiongmao.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/NegPro_V2.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_NegSeqPhaseAdj_V10/NegSeqPhaseAdj_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/OffDly_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_OnDelay2s_V11/OnDelay2s_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_OnDelay4s_V11/OnDelay4s_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_InvControlLoop3L_V40a/PWMTime_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_PhaseSequenceDetect_V10/PhaseSequenceDetect_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_VsgCtrlLoopV32/PluseV1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/PrdDelay256V2_0.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/sio_wizard_0/Pulse50x1_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_PulseSource_V15/PulseSource_V16Z.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch4_V10/RMSP64Ch4_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch8_V10/RMSP64Ch8_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/RR_VZ1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RelayPulseCtrl_V10/RelayPulseCtrl_CH4_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_SinTab8192_V11/RomP8192/RomP8192.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch4_V10/SimpDualPortRAM_Wrapper_256x24b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP32Ch16_V10/SimpDualPortRAM_Wrapper_512x12b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP128Ch4_V11/SimpDualPortRAM_Wrapper_512x16b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch8_V10/SimpDualPortRAM_Wrapper_512x24b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/SimpDualPortRAM_Wrapper_generic.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/SimpDualPortRAM_Wrapper_singlebit.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch4_V10/SimpleDualPortRAM_256x24b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP32Ch16_V10/SimpleDualPortRAM_512x12b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_AverFilterP128Ch4_V11/SimpleDualPortRAM_512x16b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_RMSP64Ch8_V10/SimpleDualPortRAM_512x24b.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/SimpleDualPortRAM_generic.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/SimpleDualPortRAM_singlebit.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_SinTab8192_V11/SinTab8192.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_SinTab8192_V11/SinTab8192_V11.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_SoftStartChn1b12_V10/SoftStartChn1b12_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Work_StateOnCheck_CH4_V10/StateOnCheck_CH8_V10.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/Temp2DrvLogic_V12_3L.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/UI_PQ_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/URef_V1.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/XvrtIq_VZ6T.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/fPuQ_VZ5T.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/new/sub_18to16.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/uart_rx.v
  D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/imports/src/uart_tx.v
}
read_ip -quiet D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/sintab/sintab.xci
set_property used_in_implementation false [get_files -all d:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/sintab/sintab_ooc.xdc]

read_ip -quiet D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/mmcm0/mmcm0.xci
set_property used_in_implementation false [get_files -all d:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/mmcm0/mmcm0_board.xdc]
set_property used_in_implementation false [get_files -all d:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/mmcm0/mmcm0.xdc]
set_property used_in_implementation false [get_files -all d:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/sources_1/ip/mmcm0/mmcm0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/constrs_1/imports/xdc/io.xdc
set_property used_in_implementation false [get_files D:/XiongMao2025/SHR/20250305_JinYang_newADdrvToYiChunPWM/20250303_JinYang_newADdrv.srcs/constrs_1/imports/xdc/io.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NEPCS_3000_S7 -part xc7s75fgga484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NEPCS_3000_S7.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NEPCS_3000_S7_utilization_synth.rpt -pb NEPCS_3000_S7_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
