// -------------------------------------------------------------
// 
// File Name: D:\FPGA_MZ\AnalogMonitorWarn_V10\SimpDualPortRAM_Wrapper_generic.v
// Created: 2025-02-10 21:10:58
// 
// Generated by MATLAB 9.1 and HDL Coder 3.9
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpDualPortRAM_Wrapper_generic
// Source Path: AnalogMonitorWarn_V10/AnalogMonitorWarn_V10/SimpDualPortRAM_Wrapper_generic
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimpDualPortRAM_Wrapper_generic
          (
           g_clk,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout
          );


  parameter AddrWidth = 1;
  parameter DataWidth = 1;

  input   g_clk;
  input   signed [DataWidth - 1:0] wr_din;  // parameterized width
  input   [AddrWidth - 1:0] wr_addr;  // parameterized width
  input   wr_en;  // ufix1
  input   [AddrWidth - 1:0] rd_addr;  // parameterized width
  output  signed [DataWidth - 1:0] rd_dout;  // parameterized width



  SimpleDualPortRAM_generic   #  (.AddrWidth(AddrWidth),
                                  .DataWidth(DataWidth)
                                  )
                              u_SimpleDualPortRAM_generic   (.g_clk(g_clk),
                                                             .wr_din(wr_din),
                                                             .wr_addr(wr_addr),
                                                             .wr_en(wr_en),  // ufix1
                                                             .rd_addr(rd_addr),
                                                             .rd_dout(rd_dout)
                                                             );

endmodule  // SimpDualPortRAM_Wrapper_generic

